### ISSUE TITLE
What are the compatible Linux Distro?

### ISSUE THREAD

**Issue by yap241986** [AsahiLinux/asahi-installer#106]
i have installed "UEFI environment only (m1n1 + U-Boot + ESP)", when I installed it I headed that I can install a linux distro from usb, but what linux distro?

**Comment by op06072** [comment]
> "UEFI 환경 전용(m1n1 + U-Boot + ESP)"을 설치했습니다. 설치할 때 USB에서 Linux 배포판을 설치할 수 있다고 생각했는데 어떤 Linux 배포판인가요?



> i have installed "UEFI environment only (m1n1 + U-Boot + ESP)", when I installed it I headed that I can install a linux distro from usb, but what linux distro?

Specially edited distro that has asahi repo.

**Comment by yap241986** [comment]
can you share with me a list of distros?

**Comment by op06072** [comment]
> can you share with me a list of distros?

arch
debian
etc...

check out the homepage's announcement

**Comment by yap241986** [comment]
Thanks
