### ISSUE TITLE
"min" `diskutil apfs resizeContainer` fails on a brand new M2 MacBook Pro

### ISSUE THREAD

**Issue by alyssais** [AsahiLinux/asahi-installer#116]
**I don't _think_ this is a duplicate of any existing issue, because the existing issues about partitioning seem to be about stuff like Time Machine snapshots, and I'm using a brand new machine — literally the first thing I'm doing with it after getting through the setup is running the Asahi installer.**

System is an M2 MacBook Pro, 24GB/2TB.

```
Choose an existing partition to resize:
  1: APFS [Macintosh HD] (2.00 TB, 6 volumes)
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
» Partition: 1

We're going to resize this partition:
  APFS [Macintosh HD] (2.00 TB, 6 volumes)
  Total size: 2.00 TB
  Free space: 1.97 TB
  Minimum free space: 1.00 GB
  Minimum total size: 30.06 GB (1.51%)

Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (50%): min

Resizing will free up 1.97 TB of space.

Note: your system may appear to freeze during the resize.
This is normal, just wait until the process completes.
» Continue? (y/N): y 

Started APFS operation
Aligning shrink delta to 1,965,156,540,416 bytes and targeting a new physical store size of 30,061,625,344 bytes
Determined the minimum size for the targeted physical store of this APFS Container to be 31,406,948,352 bytes
Error: -69521: Your APFS Container resize request is below the APFS-system-imposed minimal container size (perhaps caused by APFS Snapshot usage by Time Machine)
Failed to run process: diskutil apfs resizeContainer disk0s2 30061625344
```

[installer.log](https://github.com/AsahiLinux/asahi-installer/files/9142779/installer.log)

**Comment by marcan** [comment]
"min" isn't really supposed to work in expert mode; it's assumed you know what you're doing and will choose a reasonable partition size for macOS. I guess we could increase the minimum slack to 5GB or something, but either way it's kind of ridiculous leaving so little space for macOS.

**Comment by marcan** [comment]
I guess we should probably just remove the "min" option in expert mode...

**Comment by alyssais** [comment]
Or at least, the installer shouldn't still say in expert mode:

```
  min  - Shrink macOS as much as (safely) possible
```

Maybe there's a different term that could be used, that would mean the same in both expert and non-expert mode?  I can imagine I'm not the only person who needs to use expert mode but would still like to use the suggested minimum macOS size.
