### ISSUE TITLE
I wonder how to update my SFR's version(it is 21.6.79.0.0,0)

### ISSUE THREAD

**Issue by DRECAO** [AsahiLinux/asahi-installer#117]

**Comment by DRECAO** [comment]
During the installation, it failed because of my SFR'version.The version is 21.6.79.0.0,0 now.And it needs to be updated to 21.6.81.2.0,0.But I don't know how to update it.

**Comment by marcan** [comment]
What machine is this? Please attach the installer log. The installer prompts you to install a specific macOS version if yours is too old.

**Comment by DRECAO** [comment]
My machine is M1 MacBook Pro , MacOS version is 12.4.
Below is the installer log:
Bootability failed Error Domain=BYErrorDomain Code=105 "SFR update required to make volume bootable" UserInfo={NSLocalizedDescription=SFR update required to make volume bootable, current=21.6.79.0.0,0, target=21.6.81.2.0,0, BYErrorHint=SFRUpdateRequired}

**Comment by marcan** [comment]
Did you install in expert mode? If so, what did you pick for boot firmware?

**Comment by DRECAO** [comment]
yes,I installed in expert mode.I picked 12.4 for boot firmware.

**Comment by DRECAO** [comment]
Oh, maybe I can try 12.3.

**Comment by marcan** [comment]
Pro tip: don't pick non-default choices in expert mode if you are not, in fact, an expert ;)

But there was indeed a bug that made 12.4 appear when it shouldn't have. That is now fixed.

**Comment by DRECAO** [comment]
OK,thank you.
