### ISSUE TITLE
How do I get what Linus has?

### ISSUE THREAD

**Issue by seamusdemora** [AsahiLinux/asahi-installer#125]
Just read an [interesting article](https://www.theregister.com/2022/07/31/linux_5_19/?td=keepreading) that features this project and an old developer we've all heard about. I imagine documentation isn't a top priority now, but is there enough to provide even a top-level installation guide? If so, where can I find it.

**Comment by marcan** [comment]
If you mean Linux on these machines in general, we've had an installer released since March linked from asahilinux.org.

If you mean Fedora specifically, that's listed [here](https://github.com/AsahiLinux/docs/wiki/SW%3AAlternative-Distros).
