### ISSUE TITLE
USB Keyboard & Mouse not working after install on Mac Studio (so can't do post-install setup)

### ISSUE THREAD

**Issue by bnlawrence** [AsahiLinux/asahi-installer#127]
Hi

This is by way of a bug report. It may or may not be an edge case.

(Thanks for all the good work. I am not really expecting you to directly address this, but figure all feedback is useful, will be happy to attempt it again in a few weeks and hope it works then. I'll let you know.)

So, installing onto a Mac Studio (2022)with an M1 Max running Monterey 12.5.1
- I installed using the ```curl https://alx.sh | sh``` method (24 August 2022).
-  Everything went well (with keyboard and mouse working for the recovery step etc), until the first "real boot" with Asahi Linux, where things went through the grub loader (but the keyboard was already not working) so by the time we got to the GUI of course the keyboard and mouse didn't work.
- This is via a USB KVM, so I retried for a few cycles with the (USB-A) keyboard and mouse connected directly to see if that was relevant. It appears not.

It's not obvious to me if this is a "configuration something" I should try to fix from "the Mac side" or something more fundamental. Apologies if there is documentation on this, or this is the wrong place to report.

**Comment by bnlawrence** [comment]
Ah, well, I should have read more closely, you do make it clear that:

> You can expect most of the hardware to work as you’d expect (on par with the Mac Mini), except for the front USB ports on the M1 Max model and the Type A ports on all models (these are blocked on the special firmware upload support also needed for the 4-port version of the M1 iMac - it’s on the list).

I will investigate putting them through a dongle of some sort ...

**Comment by bnlawrence** [comment]
Ok, so using a Letscom dongle introduces a new problem.  The Asahi Linux boot loader gets stuck in an infinite loop
![IMG_1573](https://user-images.githubusercontent.com/1792815/186384595-bb0f0689-d074-441e-aeef-97bd748ed414.jpg)
(Hopefully you don't really need the numbers, it's hard to grab a photo as it's only up for a fraction of a second b4 a reboot is triggered.)

**Comment by jannau** [comment]
Does a connected USB device is a storage (sdcard reader or option to install a ssd, etc.)? This looks like an issue in u-boot that we have recently fixed. Please try to boot without any usb decides connected, connect them once linux is booted and the update the system with `pacman -Syu`. After that it should be possible to boot with all usb devices connected.

**Comment by bnlawrence** [comment]
Thanks. That has fixed the problem. (Yes, the dongle had a card reader on it.)
