### ISSUE TITLE
SSL error (probably dupe)

### ISSUE THREAD

**Issue by aidansstuff** [AsahiLinux/asahi-installer#130]
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>

`CONNECTED(00000006)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
verify return:1
depth=0 CN = updates.cdn-apple.com, O = Apple Inc., ST = California, C = US
verify return:1
---
Certificate chain
 0 s:CN = updates.cdn-apple.com, O = Apple Inc., ST = California, C = US
   i:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Nov 17 02:48:56 2021 GMT; NotAfter: Dec 17 02:48:55 2022 GMT
-----BEGIN CERTIFICATE-----
MIIICDCCBvCgAwIBAgIQWHe/1nukG6m/X7o9jPAeRDANBgkqhkiG9w0BAQsFADBi
MRwwGgYDVQQDExNBcHBsZSBJU1QgQ0EgMiAtIEcxMSAwHgYDVQQLExdDZXJ0aWZp
Y2F0aW9uIEF1dGhvcml0eTETMBEGA1UEChMKQXBwbGUgSW5jLjELMAkGA1UEBhMC
VVMwHhcNMjExMTE3MDI0ODU2WhcNMjIxMjE3MDI0ODU1WjBXMR4wHAYDVQQDDBV1
cGRhdGVzLmNkbi1hcHBsZS5jb20xEzARBgNVBAoMCkFwcGxlIEluYy4xEzARBgNV
BAgMCkNhbGlmb3JuaWExCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAtfIvwR0yp5WRIqJuOlSOf1kD058lMxV84wamr2XBamj+2/Lx
pyf9k8tSSbSwizSx14ZLFr1PCXpszRYY3QlCZhZ65WviI1//A5kplQX2xGj0AGVL
D/uW0HIWqn8vfPb6hpBVfh6s4OFkxAdBKpnn7fuiiZ1iOnNaH+3nJLd6K78a9fcQ
ZzfTXeTSBpRQdH94f9d/h4kfV0geFZxZKDHe3mwop6E+B0pajOEAZe5JHL3sTwaC
/4NhPZbiN2lxWLvhX+jvvKKPDisvWtpkUuplFaHIq/hHon2s5p3KGUYbu+fBe5PU
/b2ukUru7seEM5MKIwyCVwFnOrZ1aRMsl3+iKwIDAQABo4IEwzCCBL8wDAYDVR0T
AQH/BAIwADAfBgNVHSMEGDAWgBTYepREfJBwkBae3RecAUQDhtYqKTCBuQYIKwYB
BQUHAQEEgawwgakwNwYIKwYBBQUHMAKGK2h0dHA6Ly9jZXJ0cy5hcHBsZS5jb20v
YXBwbGVpc3RjYTJnMV9iYy5jZXIwNAYIKwYBBQUHMAKGKGh0dHA6Ly9jZXJ0cy5h
cHBsZS5jb20vYXBwbGVpc3RjYTJnMS5kZXIwOAYIKwYBBQUHMAGGLGh0dHA6Ly9v
Y3NwLmFwcGxlLmNvbS9vY3NwMDMtYXBwbGVpc3RjYTJnMTI3MCAGA1UdEQQZMBeC
FXVwZGF0ZXMuY2RuLWFwcGxlLmNvbTCCAQcGA1UdIASB/zCB/DAIBgZngQwBAgIw
ge8GCiqGSIb3Y2QFCwQwgeAwNwYIKwYBBQUHAgEWK2h0dHBzOi8vd3d3LmFwcGxl
LmNvbS9jZXJ0aWZpY2F0ZWF1dGhvcml0eS8wgaQGCCsGAQUFBwICMIGXDIGUUmVs
aWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBh
Y2NlcHRhbmNlIG9mIGFueSBhcHBsaWNhYmxlIHRlcm1zIGFuZCBjb25kaXRpb25z
IG9mIHVzZSBhbmQvb3IgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRz
LjATBgNVHSUEDDAKBggrBgEFBQcDATA3BgNVHR8EMDAuMCygKqAohiZodHRwOi8v
Y3JsLmFwcGxlLmNvbS9hcHBsZWlzdGNhMmcxLmNybDAdBgNVHQ4EFgQUJncP5LXl
SRO18kBkDPOPpq3oQREwDgYDVR0PAQH/BAQDAgWgMCwGCiqGSIb3Y2QGMAEEHgwc
MS4yLjg0MC4xMTM2MzUuMTAwLjYuMjcuNDAuMjCCAfgGCisGAQQB1nkCBAIEggHo
BIIB5AHiAHcAUaOw9f0BeZxWbbg3eI8MpHrMGyfL956IQpoN/tSLBeUAAAF9K9VD
BQAABAMASDBGAiEAjUJ1wY9WLvDMs7YkAJo3kxwWbh25wxBZH/NPcPSczS4CIQDx
x0Zw2d41QsMqj1QlPsa8pC7ACinIRLTf2WJJksbABQB2ACl5vvCeOTkh8FZzn2Ol
d+W+V32cYAr4+U1dJlwlXceEAAABfSvVQmUAAAQDAEcwRQIhAMS2YRn9dbmgG8+Z
e4ra7OUQwOfX6yp+GgfFaQ5m/n1kAiAVbijdwvIWFDBW2F0/Df8Ih8o//Oh14kKo
PHvEckVr2QB3AEHIyrHfIkZKEMahOglCh15OMYsbA+vrS8do8JBilgb2AAABfSvV
QqYAAAQDAEgwRgIhAP0ZRlDhW9o3wcheDnmbttnpwOUQD34dlFqfA3KFIv5yAiEA
r4RN+z/cjFWk+1ai/csbaRXf9sgSySmIGPTAevLqEYEAdgDfpV6raIJPH2yt7rhf
Tj5a6s2iEqRqXo47EsAgRFwqcwAAAX0r1ULUAAAEAwBHMEUCIQDsXihjpBVRrZd4
rBXb0Co435B5H0SlWjLNLo6Wn4gZrgIgfSlVsbVaBv5m5y56N+4biJeTXQow5CEp
RWnDfyztrYIwDQYJKoZIhvcNAQELBQADggEBAKxHkLCzRynwzJVWjcuamHvljp+d
SLKaKpYgc8xI3ktoXOG56On1XmSJY7zAy++RdG6t9y6H7VroF3EdfGSC8bqO69GN
WPFOs9Jw2OmM6cXuaZzozg2jIExrvDOZ4OMadqH1N7b5A/biyO15jPAbh3PIT56x
l0AZx76LPbfZ0bcSvHeTsvZLtwLpfh5Q46bxQFcTpV2yvwWYM8hSsLgRwAddh88A
jPIvCLyGewijgevR80lRXsk4oOKeqRYy8BPrKZfLp7dBb177938MMuuznsWekISL
HLOXg4ErZzhd2U371thzVlC25MVuyBe7FAtDWEb3BPAmvsHRHZ9NBGLgScw=
-----END CERTIFICATE-----
 1 s:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
   i:C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Dec 12 12:00:00 2018 GMT; NotAfter: May  7 12:00:00 2025 GMT
-----BEGIN CERTIFICATE-----
MIIEnjCCA4agAwIBAgIQBVLH7/7sKSup8Th7B6+SnzANBgkqhkiG9w0BAQsFADBa
MQswCQYDVQQGEwJJRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJl
clRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTE4
MTIxMjEyMDAwMFoXDTI1MDUwNzEyMDAwMFowYjEcMBoGA1UEAxMTQXBwbGUgSVNU
IENBIDIgLSBHMTEgMB4GA1UECxMXQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzAR
BgNVBAoTCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEA0JOhHUdDIBayC2vrw9W06MeYzfPev+hN6eM2gAf8RRtq
fEWGrlbTpAl/YQ1rXX5Sa320yDnE9Gc694POGW+GL35FfkccZ1LKlQVd4jZRhcDU
Z4A1bxXdPv0d0v2PNFDY7HYqvuPT2uT9yOsoApYRlxdhHOnEWTtC3DLRCR3aptFD
hv9esryMz2bbAYsCrpRI8ziP/eoyqAjshpdRlCQ+SUmWU+h5oUCB6QW7k5VR/OP9
fBFL954IsxVJFQf50Tegm0sy9rXE3GrR/Art9uDFKaCoi3H+DZK8/lRwGAptx+0M
+8ktBsOMhfzLhlzWNo4Siwl/+xkaONXwlDB6D6aM8wIDAQABo4IBVjCCAVIwHQYD
VR0OBBYEFNh6lER8kHCQFp7dF5wBRAOG1iopMB8GA1UdIwQYMBaAFOWdWTCCR1jM
rPoIVDaGezq1BE3wMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcD
AQYIKwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADA0BggrBgEFBQcBAQQoMCYw
JAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTA6BgNVHR8EMzAx
MC+gLaArhilodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vT21uaXJvb3QyMDI1LmNy
bDBbBgNVHSAEVDBSMAwGCiqGSIb3Y2QFCwQwCAYGZ4EMAQICMDgGCmCGSAGG/WwA
AgQwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAN
BgkqhkiG9w0BAQsFAAOCAQEAWgDobaZ4Dq8zSOdyWvCa+Tad60OIwE9qkz2o33KF
CcAM/CvxXrcXTTYo9VJHninE+G9SguIdukkDDAOHMT8WvsqomydMXknQJVbREOAX
KUKgS5q0/9ou9N1FjJvkhPGFzAbuLnSJtLomfJPxHW4h3l6bdliQodVQXd3xUbXR
qTKNUbF9bIh4601+KhyZL0u0B/eTppf/1O5S+qFAyRADr1lvfIeNHZv11iyf4u7e
uLBsXjyT3vPwxrihpAwB5pu/DhJWh4iv70Q7pcvAaRRfiJgMj3A0fFgvqvGbW9jm
t04+Cr/PjpWeMFt3KKj3DRh4jJKjJUGt+JxdGGJ4tCGyCw==
-----END CERTIFICATE-----
---
Server certificate
subject=CN = updates.cdn-apple.com, O = Apple Inc., ST = California, C = US
issuer=CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3795 bytes and written 391 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)`

I think its probably cause by my school's internet SSL certificate, it's not blocked because I can access it manually but something is not working here. is there a way to install without an SSL connection?
Mabey being able to pick a certificate to use when installing could be handy as my school has a certificate.

**Comment by aidansstuff** [comment]
Choose an OS to install:
  1: Asahi Linux Desktop
  2: Asahi Linux Minimal (Arch Linux ARM)
  3: UEFI environment only (m1n1 + U-Boot + ESP)
» OS: 1

Downloading OS package info...
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 852, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 704, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 820, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 236, in action_install_into_free
    self.osins.load_package()
  File "/private/tmp/asahi-install/osinstall.py", line 44, in load_package
    self.ucache = urlcache.URLCache(package)
  File "/private/tmp/asahi-install/urlcache.py", line 23, in __init__
    self.size = self.get_size()
  File "/private/tmp/asahi-install/urlcache.py", line 35, in get_size
    fd = request.urlopen(req)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/9441078/installer.log)

**Comment by marcan** [comment]
In this case the cert that failed verification isn't the Apple one, it's the one from our CDN. If you're still having this problem, you can try running `openssl s_client -showcerts -connect cdn.asahilinux.org:443 < /dev/null` and paste the output.

If your school is doing cert MITM though (they don't seem to for Apple, but maybe they whitelist certain domains?), sorry, we're never going to support that. It is a major security hole and your school shouldn't be doing that, plus there's no easy way for us to import the OS CA store into Python at launch right now.

**Comment by marcan** [comment]
Closing as stale, please ping if this is still happening with a cert dump.
