### ISSUE TITLE
Docker/Podman compatibility.

### ISSUE THREAD

**Issue by chadbrewbaker** [AsahiLinux/asahi-installer#140]
https://github.com/docker/for-mac/issues/6512

Could you run cat /proc/cpuinfo for M1 and paste the output here? I would like to get it fixed for docker and podman on OSX.

Also, is there an official Ashanti Linux docker container? If not it would be great to have one with all the perf tooling properly supported.

**Comment by jannau** [comment]
This doesn't make any sense, The CPU features reported by linux running on M1 baremetal have little to do with the features reported by the virtualized CPU used by docker on macos.

A docker image for AsahiLinux doesn't make much sense. The only differences compared to ArchLinux ARM are related to running ArchLinux ARM on Apple silicon hardware. There is no significant difference in the user space.

**Comment by chadbrewbaker** [comment]
Could you run cat /proc/cpuinfo for M1 under Ashanti and paste the output here?

Yes - upstream issue in QEMU for both podman and docker. For now the most simple workaround is a link shim to fake /proc/cpuinfo. 

Why doesn't it make sense to have a linux container image for Ashanti as a distro? I am guessing there are significant modifications beyond upstream Arch Linux?

**Comment by jannau** [comment]
There are no significant differences to ArchLinux ARM: in https://github.com/AsahiLinux/PKGBUILDs are all extra and different packages. Changes to mkinitcpio and libunwind are already merged in ArchLinux ARM, the remaining packages are for dealing with HW (linux-asahi, uboot-asahi, m1n1, asahi-fwextract, lzfse, asahi-scripts) or are distro / installer packages.

BTW: the project is called **Asahi Linux**, hard to take someone seriously who consistently misspells the project they are interacting with
