### ISSUE TITLE
Install Script Failed To Run Process : diskutil apfs resizeContainer

### ISSUE THREAD

**Issue by 0neP1us** [AsahiLinux/asahi-installer#144]
![image](https://user-images.githubusercontent.com/101807511/197705468-ec7c3206-7695-4cd1-83d3-2ace0fbc5475.png)

**Comment by 0neP1us** [comment]
I forgot about the log file sorry! 
I will get right when i get home

**Comment by marcan** [comment]
The message tells you what's wrong, it's mentioned in the [FAQ](https://github.com/AsahiLinux/docs/wiki/FAQ#your-apfs-container-resize-request-is-below-the-apfs-system-imposed-minimal-container-size-perhaps-caused-by-apfs-snapshot-usage-by-time-machine).
