### ISSUE TITLE
Not able to shrink my disk for install asahi linux

### ISSUE THREAD

**Issue by dayo05** [AsahiLinux/asahi-installer#147]
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/9917510/installer.log)
I'm just trying to install asahi linux on my M1 pro based Macbook pro, I want to shrink my SSD to install that. But, I get this error message with force-exiting.

**Comment by marcan** [comment]
The console log would tell you what the problem is; this is explained in the [FAQ](https://github.com/AsahiLinux/docs/wiki/FAQ#i-get-an-error-during-the-macos-resize-step-of-the-installer). The situation is already improved for the upcoming installer release.
