### ISSUE TITLE
macos 13.0 diskutil exit code 1

### ISSUE THREAD

**Issue by fredlahde** [AsahiLinux/asahi-installer#159]
I tried the installer on a M1 MacBook Air. 

It crashed with 
```
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '395507138560']' returned non-zero exit status 1.
```
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/10047683/installer.log)

**Comment by fredlahde** [comment]
Now looking at https://github.com/AsahiLinux/asahi-installer/blob/main/src/main.py#L71-L76 it seems that 13.0 isn't supported yet officially anyway. 

In that case, it might be an idea, to let the user know right at the beginning

**Comment by fredlahde** [comment]
Also, this is the output of the installer now, regarding partitions:

```
Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (494.38 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v13.0.1 [disk3s1, 8721AC1C-7D09-4CAE-B9CC-CD66E97C2F33]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v13.0.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume
```

**Comment by marcan** [comment]
You need to look at the Terminal output, which will actually tell you what the diskutil problem was.
