### ISSUE TITLE
Bootability failed when trying to install EFI stack

### ISSUE THREAD

**Issue by quisys** [AsahiLinux/asahi-installer#162]
I'm getting the error `Bootability failed Error Domain=BYErrorDomain Code=103 "Owner authentication is required" UserInfo={BYErrorHint=LocalAuthenticationRequired, NSLocalizedDescription=Owner authentication is required}` when trying to install the minimal EFI stack. I am absolutely certain I'm entering my root password correctly. What's going on?

**Comment by marcan** [comment]
That sounds like your admin user isn't actually a machine owner. I'm not entirely sure exactly how all this works, since it's not very well documented on Apple's part. Do you have any other admin users, e.g. the first one created when you first set up macOS?

**Comment by Consistos** [comment]
I'm also having this issue, would it be possible to allow to log in as the machine owner? Nothing bad would happen if I reboot without the OS being put as the default boot volume? or the installation is blocking before important steps? (I'm installing Ubuntu Asahi but I don't think it makes a difference).

**Comment by eslerm** [comment]
hi @Consistos 

I don't fully understand your question, but it sounds like you have the same error message that was reported before.

Are there other macOS users on you system? Are any of them admin accounts? As marcan is suggesting, I would try running the script under those user admin accounts (after cleaning up the previous install). If one of those user admin accounts work, it is (iiuc) the "machine owner" account.

**Comment by Consistos** [comment]
I'm in the situation marcan described (2 admin users, running the set-up script on the 2nd (1st is imported from migration assistant). According to diskutil it seems to have the same partitions as other asahi Linux install so maybe this is not an issue and it is just not set as the default install. I don't see how booting it could result in corrupted boot for others OSes as it is not managed by it as far as I know, but I want to be 100 % sure given I have no backup for now.
```
dev/disk7 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +2.5 GB     disk7
                                 Physical Store disk0s12
   1:                APFS Volume Ubuntu - Data           839.7 KB   disk7s1
   2:                APFS Volume Ubuntu                  1.1 MB     disk7s2
   3:                APFS Volume Preboot                 65.7 MB    disk7s3
   4:                APFS Volume Recovery                1.8 GB     disk7s4
```
