### ISSUE TITLE
Unable to set partition size

### ISSUE THREAD

**Issue by lodisy** [AsahiLinux/asahi-installer#169]
Hello, pretty new to this, but I don't know why this happens:

<img width="595" alt="Screenshot 2022-12-13 at 8 26 35 AM" src="https://user-images.githubusercontent.com/8101584/207196615-ab917c79-9b8b-4f1f-8de1-570e7b5755c0.png">

```
We're going to resize this partition:
  APFS [Macintosh HD] (994.66 GB, 6 volumes)
  Total size: 994.66 GB
  Free space: 684.03 GB
  Available space: 0 B
  Overhead: 646.02 GB
  Minimum total size: 994.66 GB (100.00%)
```

**Comment by marcan** [comment]
There is a link at the top of the screenshot telling you what to do. Please read the messages.
