### ISSUE TITLE
Size is too small/large no matter what size inputed

### ISSUE THREAD

**Issue by BloodHarmony** [AsahiLinux/asahi-installer#170]
No matter the size that is inputted during installation, it describes that the partition is too small or too large. It is basically impossible to resize the partition.
<img width="1026" alt="Screenshot 2022-12-17 at 11 28 19 AM" src="https://user-images.githubusercontent.com/117941382/208254762-4d8f11b2-9257-459b-a97d-6355c5ae1fae.png">

**Comment by marcan** [comment]
Read the prior messages. It told you what the problem was and gave you a link describing how to solve it.

**Comment by Kameania** [comment]
@marcan I am having the same problem, would you be able to help me out? Can you send me the link to the solution?

**Comment by Keeyuu** [comment]
I am having the same problem, would you be able to help me out?
