### ISSUE TITLE
Cannot install on Mac Studio M1 Ultra

### ISSUE THREAD

**Issue by scv9** [AsahiLinux/asahi-installer#175]
Hi

I end up in a bootloop. Screen shows nothing, so I cannot provide any info, except I have successully installed asahi on MacBook Pro M1 Max.

Machine Spec:
- 20C CPU, 48C GPU, 64GB, 1TB

**Comment by marcan** [comment]
Please give more details about what you have experienced. Is this bootloop before or after stage 2 of the installation? How do you know it's a bootloop if the screen shows nothing? What kind of screen are you using, and how is it connected?

**Comment by scv9** [comment]
I have LG Ultrafine 5K connected via thunderbolt.

As I did with MBP, process all steps, following provided instructions. 

As suggested, after shutdown wait 15 secs, power-on Mac Studio, choose Asahi Linux, it booted me into kinda recovery env. Entered passwd, policies applied successfully. Then it asks for reboot, after it I noticed my Led power down and up again every ~15 sec. It is approx time to reach asahi bootloader. As I know this is a main boot device, I made a conclusion this is a bootloop.

**Comment by marcan** [comment]
*Sigh*

Thunderbolt displays are not supported. Please read the [Feature Support](https://github.com/AsahiLinux/docs/wiki/Feature-Support) page before filing spurious bug reports.

**Comment by scv9** [comment]
Thank you for your time.

**Comment by scv9** [comment]
But why it reboots if it just cannot recognize video output device? Is it normal?

**Comment by jannau** [comment]
the thunderbolt display should not result in a boot loop. Does the boot loop goes away without display connected? If yes, please try connecting another display with the HDMI port, keep the LG Ultrafine 5K connected via thunderbolt and film the screen. My best guess is that u-boot crashes due to one of USB devices in the display.

**Comment by scv9** [comment]
I plugged hdmi monitor, with all other devices remain plugged. And magic - all works.On 2 Feb 2023, at 15:43, Janne Grunau ***@***.***> wrote:﻿
the thunderbolt display should not result in a boot loop. Does the boot loop goes away without display connected? If yes, please try connecting another display with the HDMI port, keep the LG Ultrafine 5K connected via thunderbolt and film the screen. My best guess is that u-boot crashes due to one of USB devices in the display.

**Comment by scv9** [comment]
One more thing - as you said - sometimes it crashes during u-boot xHCI devices discovery.
