### ISSUE TITLE
Error Downloading Data during OS Install

### ISSUE THREAD

**Issue by AbuTabla** [AsahiLinux/asahi-installer#176]
When installing OS under copying from esp into disk0s4 partition, I get an error claiming to have an incomplete read. I've factory resetted to make sure there was enough space on the computer. 

[installer.log](https://github.com/AsahiLinux/asahi-installer/files/10669143/installer.log)

**Comment by marcan** [comment]
That's usually a network problem. Please try again and see if the problem persists.

If it still happens, please run this command from macOS and paste the output:

```
curl -fOvvi https://cdn.asahilinux.org/os/asahi-plasma-20221122-4.zip && ls -al asahi-plasma-20221122-4.zip && shasum asahi-plasma-20221122-4.zip
``
If it still happens, try downloading [this](https://cdn.asahilinux.org/os/asahi-plasma-20221122-4.zip) link and check the size (it should be 3454689184 bytes) and sha1sum (it should be d320280eeea919da1c9771cbeed116637f0cf1fe).

**Comment by ZerdoX-x** [comment]
For me downloading 3gb zip from asahi cdn shows estimated time more than 1 day... That's the reason why I encounter the same problem. fast.com speed test shows 18Mbps, which is not as fast but should be enough for this type of task.
