### ISSUE TITLE
After an unsuccessful installation almost half of my ssd's storage is nowhere to be found,I use a mba m1

### ISSUE THREAD

**Issue by Dushyxnt** [AsahiLinux/asahi-installer#177]

**Comment by marcan** [comment]
Please read the [Partitioning cheatsheet](https://github.com/AsahiLinux/docs/wiki/Partitioning-cheatsheet) page to learn how to manage your partitions manually. Do not use the *Disk Utility* app, as it is completely broken (this is an Apple bug we can't do anything about).
