### ISSUE TITLE
Installation error | Partition

### ISSUE THREAD

**Issue by jdoppelhofer** [AsahiLinux/asahi-installer#182]
```
Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (494.38 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v13.2.1 [disk3s1s1, D09A2B18-B0CB-487A-A239-A797EFC56A50]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v13.2.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (r): r


We're going to resize this partition:
  APFS [Macintosh HD] (494.38 GB, 6 volumes)
  Total size: 494.38 GB
  Free space: 90.95 GB
  Available space: 0 B
  Overhead: 52.95 GB
  Minimum total size: 494.38 GB (100.00%)

  Note: The selected partition has significant disk space overhead.
  This is usually caused by APFS snapshots used by Time Machine, which
  use up free disk space and prevent resizing the partition to a smaller
  size. It can also be caused by having a pending macOS upgrade.

  If you want to resize your partition to a smaller size, please complete
  any pending macOS upgrades and visit this link to learn how to manually
  delete Time Machine snapshots:

    https://alx.sh/tmcleanup

Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (min): min
Size is too large, please enter a value < 494.38 GB
» New size (min): 100%
Size is too large, please enter a value < 494.38 GB
» New size (min): 30%
Size is too small, please enter a value > 494.38 GB (100.00%)
```

**Comment by marcan** [comment]
Did you follow the instructions to delete your Time Machine local snapshots and ensure any pending updates are complete?

**Comment by jdoppelhofer** [comment]
Thank you for your advice, it removed every Time Machine Snapshots, and now I can resize the partition. But now I get an error while resizing. Is there a relation between the Time Machine error?

`Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (min): 85%

Resizing will free up 74.16 GB of space.

Note: your system may appear to freeze during the resize.
This is normal, just wait until the process completes.
» Continue? (y/N): y

Started APFS operation
Aligning shrink delta to 74,157,477,888 bytes and targeting a new container size of 420,227,317,760 bytes
Determined the minimum size for the APFS Container to be 379,399,962,624 bytes
Resizing APFS Container designated by APFS Container Reference disk3
The specific APFS Physical Store being resized is disk0s2
Verifying storage system
Using live mode
Performing fsck_apfs -n -x -l /dev/disk0s2
Checking the container superblock
Checking the space manager
Checking the space manager free queue trees
Checking the object map
Checking the encryption key structures
Checking volume /dev/rdisk3s1
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking snapshot 1 of 1 (com.apple.os.update-DCFA9E2D4E4407822BB513A874B2A2922E2DD50403877F878FA8D11CC3D57596)
Checking the fsroot tree
Checking the file extent tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s1 appears to be OK
Checking volume /dev/rdisk3s2
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s2 appears to be OK
Checking volume /dev/rdisk3s3
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s3 appears to be OK
Checking volume /dev/rdisk3s4
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s4 appears to be OK
Checking volume /dev/rdisk3s5
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the document ID tree
Checking the fsroot tree
warning: inode (id 30706142): Resource Fork xattr is missing for compressed file
warning: inode (id 31762124): Resource Fork xattr is missing for compressed file
warning: inode (id 42750245): Resource Fork xattr is missing for compressed file
warning: inode (id 80472022): Resource Fork xattr is missing for compressed file
warning: inode (id 80486965): Resource Fork xattr is missing for compressed file
error: dstream (id 13626377) does not have an associated dstream id object
error: alloced_size (4096) of dstream (id 13626377) does not match calculated size (0)
error: dstream (id 13632649) does not have an associated dstream id object
error: alloced_size (4096) of dstream (id 13632649) does not match calculated size (0)
error: dstream (id 85446702) does not have an associated dstream id object
error: alloced_size (4096) of dstream (id 85446702) does not match calculated size (0)
error: dstream (id 85749033) does not have an associated dstream id object
error: alloced_size (4096) of dstream (id 85749033) does not match calculated size (0)
error: dstream (id 85812827) does not have an associated dstream id object
error: alloced_size (4096) of dstream (id 85812827) does not match calculated size (0)
error: dstream (id 85822600) does not have an associated dstream id object
error: alloced_size (4096) of dstream (id 85822600) does not match calculated size (0)
Checking the extent ref tree
Checking the file key rolling tree
Verifying volume object map space
The volume /dev/rdisk3s5 was found to be corrupt and needs to be repaired
Checking volume /dev/rdisk3s6
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s6 appears to be OK
Verifying allocated space
Performing deferred repairs
error: dstream (id 13626377) does not have an associated dstream id object
Skipped 12/12 repairs of this type in total
Deferred repairs skipped
The container /dev/disk0s2 could not be verified completely
Storage system check exit code is 8
Error: -69716: Storage system verify or repair failed

Resize failed. This is usually caused by pre-existing APFS filesystem corruption.
Carefully read the diskutil logs above for more information about the cause.
This can usually be solved by doing a First Aid repair from Disk Utility in Recovery Mode.`

**Comment by marcan** [comment]
Again the message tells you exactly what to do.

**Comment by jdoppelhofer** [comment]
I followed the First Aid repair instructions in Disk Utility Recovery Mode, but still getting the same error message. Any suggestions on how to fix it?

**Comment by marcan** [comment]
If First Aid on the macOS APFS container doesn't fix it then you may have to wipe and reinstall the machine. This is existing APFS corruption caused by macOS bugs, so unfortunately not something we can fix or help with. If Apple's own tooling can't fix it then there's not much else we can do... you may want to file a feedback report with Apple.

**Comment by JarrydMartin** [comment]
@jdoppelhofer I was running into the same issue. 

I ran the First Aid repair in Recovery Mode, and still got the same error.

But, I was repairing the Macintoch HD volume and not the Container as @marcan said.
![image](https://github.com/AsahiLinux/asahi-installer/assets/11459942/dd0b7dae-a7fc-457e-93c5-cfa7872eda43)
You can see if you click the View button near the top left, you can expand the values and see the Container. 

Once I ran the repair on the Container, I could Partition.

So make sure to repair the Container.
