### ISSUE TITLE
urlopen error

### ISSUE THREAD

**Issue by Lo-12-ai** [AsahiLinux/asahi-installer#183]
hi , plz can you help me at this prob I don't understand what should I do so plz could you help me 
<img width="1680" alt="Screenshot 2023-03-10 at 10 35 35 AM" src="https://user-images.githubusercontent.com/120338342/224265551-050ce7a3-b854-43c3-bca8-cd313c286b88.png">

**Comment by marcan** [comment]
Sounds like a problem with your internet connection. Maybe it is filtered or otherwise blocking our server.

**Comment by Lo-12-ai** [comment]
ok what should I do ????

**Comment by marcan** [comment]
Please try on a different internet connection.
