### ISSUE TITLE
Stuck at Running proxy

### ISSUE THREAD

**Issue by Rafdor64** [AsahiLinux/asahi-installer#185]
My m1 MacBook Air 2020 is running the asahi installer but it won't go past Running proxy

![image](https://user-images.githubusercontent.com/114437115/229519406-d9c86628-7f31-43fa-b880-6043fb548c49.jpeg)

**Comment by YunlangLu** [comment]
I also meet with this trouble. But I don’t know how to solve it 😮‍💨

**Comment by marcan** [comment]
You asked for tethered proxy mode, so you got tethered proxy mode. If you want to install Asahi, then don't do that.

**Comment by 1seco** [comment]
@marcan I'm having this problem too an I have no idea what you are talking about. I never did anything about a tethered proxy mode, and I don't know how to turn it off. Could you give any help?

**Comment by 1seco** [comment]
I mean the most I have similar to a usbc connection is a dongle?

**Comment by 1seco** [comment]
OK no, to everyone here: I'm a bit stupid. You need two efi partitions. One is premade by alx.sh, and another for your distro. (I think). But this is niche stuff for stuff like your own distro or the spinoffs.
