### ISSUE TITLE
Installer saying not compatible with M2 pro (16-inch, 2023)

### ISSUE THREAD

**Issue by hwr12** [AsahiLinux/asahi-installer#189]
Hi.

I have encountered an error saying, "This device is not supported yet", while installing asahi linux on my M2 pro 16 inch(2023).
I saw in the wiki that the installer doesn't support this device yet, but the asahi linux still supports my device.
So are there any walkarounds to get the asahi linux installed on my machine or do I need to wait until the installer starts to support my machine?

<img width="550" alt="iTerm-2023 04 14 23 48-000960" src="https://user-images.githubusercontent.com/54504396/232078679-f65309f1-7c3f-44e0-9bef-cb7f8b771405.png">

**Comment by codingCoffee** [comment]
Hey @hwr12, just curious if you found any work arounds

**Comment by hwr12** [comment]
> Hey @hwr12, just curious if you found any work arounds 
>  

Nope. I closed because ashai linux just don't support M2 pro.

**Comment by Sycrosity** [comment]
Now that the wiki shows that there is now support for M2 Pro devices ([wiki link](https://github.com/AsahiLinux/docs/wiki/Feature-Support#m2-promaxultra-device-specific-support)), is there any update on when the installer will work with M2 and M2 pro devices?
