### ISSUE TITLE
installer completes but system won't boot into asahi

### ISSUE THREAD

**Issue by burkejoh** [AsahiLinux/asahi-installer#191]
I have a mini m1 running Ventura 13.3.1 (a).  I don't see any errors going through the entire install process both times I attempted the install.  After the first failure I used diskutil  to erase your partitions and repeated the entire install process.  I took the default MacOS bootloader both times.  In any case when I attempt to boot linux the screen remains blank no grub.

**Comment by marcan** [comment]
Are you using an HDMI monitor? Type C monitors are not supported yet.
