### ISSUE TITLE
Boot loop on initial install on M1 Max MBP on 13.3.1 (Z14W00106LL/A)

### ISSUE THREAD

**Issue by jcm93** [AsahiLinux/asahi-installer#192]
Hi there; as a preface, I'll emphasize that I believe I am following all install instructions correctly. When holding the power button and releasing after "Loading startup options" appears, I immediately encounter a boot loop. I'll attach a video.

My particular system is on macOS 13.3.1. It's the M1 Max MacBook Pro with the 24-core GPU, and 32GB of system memory.

I have tried running the installer multiple times to repair the installation (it thinks things are fine and just prompts me to shut down and restart as usual). I have also tried destroying the partitions the installer creates and starting completely fresh. The same issue occurs. I've also tried holding down the button longer; or shorter, to no effect. After attempting to boot 15-20 times, the recovery partition boots up luckily, and I am able to re-select macOS to boot from.

edit: As far as my installer settings, they are fairly normal. I resized my 1 TB volume to 950GB and ended up with 44 GB to install Asahi in, and selected the default Asahi desktop install. No expert mode shenanigans. Also wanted to add that this is my first attempt at installing Asahi, no prior installs.

Please let me know if there's any other information I can provide or any debugging steps I can take, happy to help however I can!

Thank you.

https://github.com/AsahiLinux/asahi-installer/assets/6864788/a104fa19-68a1-4899-8810-3144019f6e64

**Comment by jcm93** [comment]
Writing this from Asahi. Installing with 12.3.1 firmware went off without a hitch. Understand that it's a rare issue, but a posted warning somewhere in the instructions or the installer would be good. Thank you!

**Comment by PwnedC99** [comment]
Having the exact same issue on my M1 Pro Base Model MacBook Pro 16 inch. There is no way to get the 2nd stage to work even after reinstalling stage 1.

**Comment by PwnedC99** [comment]
> Writing this from Asahi. Installing with 12.3.1 firmware went off without a hitch. Understand that it's a rare issue, but a posted warning somewhere in the instructions or the installer would be good. Thank you!

How have you proceeded to install Asahi on the machine with 13.3.1? Dual Boot with older firmware and then install asahi?

**Comment by jcm93** [comment]
> > Writing this from Asahi. Installing with 12.3.1 firmware went off without a hitch. Understand that it's a rare issue, but a posted warning somewhere in the instructions or the installer would be good. Thank you!
> 
> How have you proceeded to install Asahi on the machine with 13.3.1? Dual Boot with older firmware and then install asahi?

No, the installer bundles the firmware it uses and has the option to use firmware without this issue.

Per [this tweet](https://twitter.com/AsahiLinux/status/1600862872669949952) expert mode in the installer and select the 12.3.1 firmware rather than 12.3.

**Comment by PwnedC99** [comment]
> > > Writing this from Asahi. Installing with 12.3.1 firmware went off without a hitch. Understand that it's a rare issue, but a posted warning somewhere in the instructions or the installer would be good. Thank you!
> 
> > 
> 
> > How have you proceeded to install Asahi on the machine with 13.3.1? Dual Boot with older firmware and then install asahi?
> 
> 
> 
> No, the installer bundles the firmware it uses and has the option to use firmware without this issue.
> 
> 
> 
> Per [this tweet](https://twitter.com/AsahiLinux/status/1600862872669949952), enable expert mode in the installer and select the 12.3.1 firmware rather than 12.3.

It's weird I am encountering this bug too and I can not confidently say if mine was replaced or not. Booting with 12.3.1 works. Mind telling why your board was replaced and if you know how to check if one's was replaced? 

I bought mine used and the serial all match from the system to the packaging. Maybe not only replaced boards can face this?

**Comment by jcm93** [comment]
Not sure, for replacements these days I think Apple typically flashes the same serial number present on the original packaging. If you bought it refurbished or something, seems probable it could be replaced. There might be some incantations you could feed to Terminal to determine its status, but I don't know what they'd be. If a maintainer sees this I imagine they could shed more light.

**Comment by marcan** [comment]
Use `curl https://alx.sh | EXPERT=1 sh`, enable expert mode, and select `12.3.1` firmware when prompted. This is a known issue, which will be obsolete once we switch to the next supported firmware version (13.5) for all machines.

**Comment by marcan** [comment]
I'm going to close this since Fedora has been on 13.5 for a while now and Arch will move to that version soon. Most new users should be moving to Fedora at this point.
