### ISSUE TITLE
MacbookAir M1 installer issue with Mac OS Sonoma

### ISSUE THREAD

**Issue by TongyeZhang** [AsahiLinux/asahi-installer#199]
There's an issue while I'am installing Asahi Linux on my device.(Desktop version).But unexpectedly , the minimal choice an install successfully.But there's also have many issues like network etc in using.
The log of the installing is below.
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/12061462/installer.log)

**Comment by marcan** [comment]
That sounds like your network is broken/unstable. The error there just means your computer failed to connect to our server to download the image. It's the same server as the minimal image, so if that worked then the installer is working fine and you just have an unstable connection to our CDN. That's not something we can fix on our end.
