### ISSUE TITLE
HDMI sound not working.

### ISSUE THREAD

**Issue by mydarkmatter1** [AsahiLinux/asahi-installer#200]
Mac mini M1.  The sound only works on the built-in speakers.  Hdmi does not transmit sound to TV.  Please tell me how to transfer sound via Hdmi?  Thank you!

**Comment by jannau** [comment]
This is not yet supported and considered too small of a feature to be mentioned on https://github.com/AsahiLinux/docs/wiki/Feature-Support

**Comment by mydarkmatter1** [comment]
Sorry, thanks.

**Comment by mydarkmatter1** [comment]
Sorry, thanks.

**Comment by mydarkmatter1** [comment]
Sorry, thanks

**Comment by SenseOfScience** [comment]
> This is not yet supported and considered too small of a feature to be mentioned on https://github.com/AsahiLinux/docs/wiki/Feature-Support

Is there any chance this feature could be added to the wiki?  I often wonder whether this functionality is present (has been added) or not and searching for it is difficult due to the keywords involved.

**Comment by marcan** [comment]
Not an installer issue.

**Comment by TwoxSheds** [comment]
> This is not yet supported and considered too small of a feature to be mentioned on https://github.com/AsahiLinux/docs/wiki/Feature-Support

Too small of a feature? What do you think people use computers for these days? I use mine as a media server, HDMI audio is critical for this application. Please reconsider your priorities. I also use a Mac and another Linux workstation as DAWs.

**Comment by mbeavitt** [comment]
@jannau is it not mentioned here?

https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support#hdmi-audio
