### ISSUE TITLE
Running build.sh on fedora 38 system reports an error: There are data after the end of archive

### ISSUE THREAD

**Issue by donglisi** [AsahiLinux/asahi-installer#202]
The full error is as follows:

Determining version...
Version: 3875a76
Downloading installer components...
--2023-08-05 16:07:34--  https://www.python.org/ftp/python/3.9.6/python-3.9.6-macos11.pkg
Resolving www.python.org (www.python.org)... 151.101.108.223, 2a04:4e42:1a::223
Connecting to www.python.org (www.python.org)|151.101.108.223|:443... connected.
HTTP request sent, awaiting response... 416 Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

Building m1n1...
make: Entering directory '/a/source/asahi/asahi-installer/m1n1'
make: Leaving directory '/a/source/asahi/asahi-installer/m1n1'
Copying files...
Extracting Python framework...

ERRORS:
There are data after the end of archive

gzip: stdin: unexpected end of file
cpio: premature end of archive

**Comment by marcan** [comment]
I can't reproduce this, a clean fetch and build works on F38. Maybe delete the contents of the dl/ folder and try again?

**Comment by donglisi** [comment]
Sorry, this is because I only installed p7zip (manually created /usr/bin/7z soft link) and did not install p7zip-plugins.
