### ISSUE TITLE
“Authorized user:” not recognizing my username

### ISSUE THREAD

**Issue by E-man-dev** [AsahiLinux/asahi-installer#208]
16” M1 Pro macbook with all the latest
During the step2.sh section of Asahi Linux Desktop setup, the “Authorized user:” prompt is not recognizing my username. I know the username is correct and the one I had selected, even confirmed it by going to the Startup Disk tool and clicking Unlock on my macOS boot volume.

**Comment by eslerm** [comment]
In a Mac terminal, can you run `sudo whoami` ? Are you using that password?

Are there other user accounts?

**Comment by E-man-dev** [comment]
Thank you so much! I had no idea that the username and user were different things.
