### ISSUE TITLE
Please provide clearer information on what to do next

### ISSUE THREAD

**Issue by BoKa33** [AsahiLinux/asahi-installer#211]
Hey, my macbook ran into this:

Collecting system information...
  Product name: MacBook Pro (16-inch, 2023)
  SoC: Apple M2 Max
  Device class: j416cap
  Product type: Mac14,6
  Board ID: 0x6
  Chip ID: 0x6021
  System firmware: iBoot-8422.141.2
  Boot UUID: 31B9CA51-0E8E-4E0D-BC2A-AC9382B08F7F
  Boot VGID: 31B9CA51-0E8E-4E0D-BC2A-AC9382B08F7F
  Default boot VGID: 31B9CA51-0E8E-4E0D-BC2A-AC9382B08F7F
  Boot mode: macOS
  OS version: 13.5.2 (22G91)
  SFR version: 22.7.91.0.0,0
  System rOS version: 13.5.2 (22G91)
  No Fallback rOS
  Login user: boka

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (750.00 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v13.5.2 [disk4s1s1, 31B9CA51-0E8E-4E0D-BC2A-AC9382B08F7F]
  2: (free space: 145.20 GB)
  3: APFS (2.50 GB, 0 volumes)
  4: EFI (500.17 MB)
  5: Linux Filesystem (96.47 GB)
  6: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v13.5.2 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk4s1s1) for machine authentication.

Choose what to do:
  f: Install an OS into free space
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (f): f

Choose an OS to install:
  1: Asahi Linux Desktop
  2: Asahi Linux Minimal (Arch Linux ARM)
  3: UEFI environment only (m1n1 + U-Boot + ESP)
  4: Tethered boot (m1n1, for development)
» OS: 1

Downloading OS package info...
- 

Minimum required space for this OS: 15.00 GB

Available free space: 145.20 GB

How much space should be allocated to the new OS?
  You can enter a size such as '1GB', a fraction such as '50%',
  the word 'min' for the smallest allowable size, or
  the word 'max' to use all available space.
» New OS size (max): max

The new OS will be allocated 145.20 GB of space,
leaving 0 B of free space.

Enter a name for your OS
» OS name (Asahi Linux): Asahi

Your system firmware is too old.
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1050, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 858, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1013, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 314, in action_install_into_free
    os_size = self.get_os_size_and_info(free_part.size, min_size, template)
  File "/private/tmp/asahi-install/main.py", line 359, in get_os_size_and_info
    ipsw = self.choose_ipsw(template.get("supported_fw", None))
  File "/private/tmp/asahi-install/main.py", line 467, in choose_ipsw
    p_error(f"Please upgrade to macOS {minver[0].version} or newer.")
IndexError: list index out of range
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
boka@Tuxbook ~ % 

And i cannot find any information on what to do now.

**Comment by marcan** [comment]
"Please do not file bugs if things go wrong in expert mode."
