### ISSUE TITLE
Is it possible to dual boot Asahi Fedora along with Arch Linux on an external media?

### ISSUE THREAD

**Issue by MegunaStellar** [AsahiLinux/asahi-installer#218]
I have a small internal disk for my m1 Macbook, and recently I saw a lot of new updates on the asahi, such as the webcam and the touch bar, which was exactly what I needed. I need to install it onto an external media, but I am not sure if you can update it on the external media, and if you are able to dual boot it. Also, the touch bar support shows 'fedora-asahi', so I assume you have to install the Fedora Asahi Linux in order to use it. However, I prefer using Arch, as I've been using it for a long time, and being more comfortable with it. Is there a way to install both Fedora and Arch on an external SSD, or perhaps use 'fedora-asahi' supported features on a different OS than Fedora, such as Arch?

**Comment by marcan** [comment]
The bug tracker is not an appropriate place for user support questions. Please ask on one of the community venues (Fedora Discussion, IRC, etc.).
