### ISSUE TITLE
IndexError: list index out of range in `main.py`

### ISSUE THREAD

**Issue by NAThompson** [AsahiLinux/asahi-installer#220]
Error message:

```
Your system firmware is too old.
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1050, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 858, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1013, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 314, in action_install_into_free
    os_size = self.get_os_size_and_info(free_part.size, min_size, template)
  File "/private/tmp/asahi-install/main.py", line 359, in get_os_size_and_info
    ipsw = self.choose_ipsw(template.get("supported_fw", None))
  File "/private/tmp/asahi-install/main.py", line 467, in choose_ipsw
    p_error(f"Please upgrade to macOS {minver[0].version} or newer.")
IndexError: list index out of range
```

This is a trivial bug-the successfully printed error message tells me what I need to know (though I have updated my firmware to the latest version). Nonetheless should be an easy fix.

System information:

```
Model Name:	MacBook Pro
Model Identifier:	Mac14,5
Chip:	Apple M2 Max
Total Number of Cores:	12 (8 performance and 4 efficiency)
Memory:	32 GB
System Firmware Version:	10151.1.1
```

Information printed by `main.py`:

```
Collecting system information...
  Product name: MacBook Pro (14-inch, 2023)
  SoC: Apple M2 Max
  Device class: j414cap
  Product type: Mac14,5
  Board ID: 0x4
  Chip ID: 0x6021
  System firmware: iBoot-10151.1.1
  Boot UUID: 010CAE99-E86E-4B11-8099-4B0302B2B267
  Boot VGID: 010CAE99-E86E-4B11-8099-4B0302B2B267
  Default boot VGID: 010CAE99-E86E-4B11-8099-4B0302B2B267
  Boot mode: macOS
  OS version: 14.0 (23A344)
  SFR version: 23.1.344.0.0,0
  System rOS version: 14.0 (23A344)
  No Fallback rOS
```

**Comment by gaoxiangliu** [comment]
Same issue, here is mine:
  Product name: Mac mini (2023)
  SoC: Apple M2
  Device class: j473ap
  Product type: Mac14,3
  Board ID: 0x24
  Chip ID: 0x8112
  System firmware: iBoot-10151.1.1
  Boot UUID: 7A61BD9D-B493-4043-85F3-09278C775725
  Boot VGID: 7A61BD9D-B493-4043-85F3-09278C775725
  Default boot VGID: 7A61BD9D-B493-4043-85F3-09278C775725
  Boot mode: macOS
  OS version: 14.0 (23A344)
  SFR version: 23.1.344.0.0,0
  System rOS version: 14.0 (23A344)
  No Fallback rOS

I have two questions:
1. Does Asahi support MacOS 14? This is the latest version.
2. There is a bug in the Python script, in the function choose_ipsw of main.py. When minver is empty, indexing it would cause an exception. This is where the bug is.

**Comment by gaoxiangliu** [comment]
Hi @NAThompson , thank you so much for replying and repairing. The script works if I follow your steps in the last post. One more thing, I can go to the Asahi Linux system in the recovery mode after the script finishes. And the setup is okay. But, when the device restarted and go the the Linux system, I can only see a black screen. Here is my system info:
  Product name: Mac mini (2023)
  SoC: Apple M2
  Device class: j473ap
  Product type: Mac14,3
  Board ID: 0x24
  Chip ID: 0x8112
  System firmware: iBoot-8422.141.2
  Boot UUID: 5FB57953-D8A5-4D9E-B517-4370D196A2C7
  Boot VGID: 5FB57953-D8A5-4D9E-B517-4370D196A2C7
  Default boot VGID: CB2BBA84-221A-4F10-9792-048378F9427D
  Boot mode: macOS
  OS version: 13.5 (22G74)
  SFR version: 22.7.74.0.0,0
  System rOS version: 13.5 (22G74)
  No Fallback rOS
Yes, I downgraded to MacOS 13.5.
Please let me know anything I need to provide.

Also, after I enter the Asahi Linux system after solving all the problem, can I compile a Linux kernel from kernel.org and install to modify the Linux kernel?

Thank you!

**Comment by marcan** [comment]
Everything described in this bug is a consequence of trying to install on unsupported machines. There is no bug, everything is working as intended.
