### ISSUE TITLE
M2 is here, but...

### ISSUE THREAD

**Issue by greipfruktas** [AsahiLinux/asahi-installer#221]
Hi, 
so i've found that M2 support is here for more than a year now, but when I'm trying to install Asahi I get that my device is not supported and I should read the blog about updates and device support. It runs on M2pro and July 2022 blog post is about that the M2 is here. Am I doing something wrong, or the title of release post is wrong? :)

**Comment by greipfruktas** [comment]
Not all heroes wear capes!

> Try this: [AsahiLinux/docs#82 (comment)](https://github.com/AsahiLinux/docs/issues/82#issuecomment-1758463076)

Not all heroes wear capes! Device is compatible, trying to solve partition problem which is probably caused by time machine. Thanks!

**Comment by greipfruktas** [comment]
Ok I am stuck again with my mac. I got it past partition problem, but now I get that my system firmware is too old. But its 14 Sonoma. Is there a newer one? There isn't. :|

**Comment by greipfruktas** [comment]
Yup, worked. Thanks. 
So ok, m2 is supported with buts. 

On first boot i was able to connect to my home wifi, now its gone and i can't connect to wifi. Googling...
Tried to install steam - as I understand its not possible?

**Comment by jannau** [comment]
the M2 and M2 Pro/Max/Ultra desktop devices introduced in 2023 are not supported yet. They work to some degree but do not expect support.

M2 Pro in a Mac Mini is very much a different thing than the the M2 laptops introduced in 2022. Every device has to be supported explictily.

**Comment by jannau** [comment]
> Try this: [AsahiLinux/docs#82 (comment)](https://github.com/AsahiLinux/docs/issues/82#issuecomment-1758463076)

Please do not recommend expert mode to unsuspecting users. Devices are not supported for a reason.
