### ISSUE TITLE
Anyone Can Run Asahi Linux on M2 MacMini 2023?

### ISSUE THREAD

**Issue by gaoxiangliu** [AsahiLinux/asahi-installer#222]
Hi,

I have a MacMini M2 2023 device. I tried to install Asahi Linux (Desktop, Minal, m1n1 only), but the system failed to boot (black screen, Caps Lock indicator does not flash when pressing down CapsLock key) after successfully executing the installation script and step 2 in the recovery mode (Select Asahi Linux and follow the terminal information) and restart.

Below is my system info:
Product name: Mac mini (2023)
SoC: Apple M2
Device class: j473ap
Product type: Mac14,3
Board ID: 0x24
Chip ID: 0x8112
System firmware: iBoot-8422.141.2
Boot UUID: 5FB57953-D8A5-4D9E-B517-4370D196A2C7
Boot VGID: 5FB57953-D8A5-4D9E-B517-4370D196A2C7
Default boot VGID: CB2BBA84-221A-4F10-9792-048378F9427D
Boot mode: macOS
OS version: 13.5 (22G74)
SFR version: 22.7.74.0.0,0
System rOS version: 13.5 (22G74)
No Fallback rOS

Could anyone who has similar problems share the solutions?
Thank you!

**Comment by jannau** [comment]
The Mac mini (M2, 2023) is not fully supported, see https://github.com/AsahiLinux/docs/wiki/Feature-Support

That said it you probably hit a bug in the new display init code which prevented booting. It was added on 12th and fixed on 13th. A new install now should be less broken and might even init the display but the device is still not supported. The AsahiLinux options probably boot into the display manager, the Fedora images will to but fail to display anything.
