### ISSUE TITLE
Remove KDE Plasma Apps that I won't/don't want to use

### ISSUE THREAD

**Issue by mattvisa** [AsahiLinux/asahi-installer#223]
Hello,
I am new to this and first time installing Arch. Thank you for the incredible work. I ask if there is a way to remove some of the KDE Plasma apps that I don't want to use such as many of the education apps and all of the preinstalled games apps. I tried to use the terminal, but ran into dependency issues with uninstalling games. I am not sure if KDE is integrated fully with the apps or not, but the KDE "discover" does not give me any options to remove applications. If you can point me in the right direction, I'd appreciate it as I want to "unbloat" the preinstalled KDE apps according to my own discretion if possible.
Thanks much. Matt

**Comment by mattvisa** [comment]
I get this error when I right click on an app/program and click uninstall.

![Screenshot_20231014_104232](https://github.com/AsahiLinux/asahi-installer/assets/130477370/bea2cd7e-bc7e-4b88-bfd6-e796d2f3c84e)

**Comment by liberodark** [comment]
Hi,

Please use pacman : https://wiki.archlinux.org/title/Pacman
Or iff you want GUI use pamac-gui
And leave kde discover...

Best Regards

**Comment by mattvisa** [comment]
![Screenshot_20231109_205931](https://github.com/AsahiLinux/asahi-installer/assets/130477370/ef6c01b4-54f0-40bf-8bd4-af91f198643b)
I added pamac to see if I could do this. Both in terminal (Konsole) I get errors that there are dependencies and in Pamac that make it so I can't remove anything.

**Comment by mattvisa** [comment]
This happens with each app I've tried so far, not just the one I screenshot. And again, sudo pacman -Rns <program name> gives me similar error messages for the tons of KDE apps that for me seem to clog up my vision. Probably not an urgent issue, but I would love to slim down my programs to just what I use/need.

**Comment by marcan** [comment]
The Asahi Arch KDE spin is now deprecated. Package management works the usual Arch way, please refer to general pacman usage documentation. You will have to remove the meta packages if you want to remove the packages they refer to.

For a better package management experience with better UI integration, I strongly recommend Fedora. Arch Linux is not a good choice unless you are familiar with Linux command line tools.
