### ISSUE TITLE
Unable to install Asahi Linux [MacBook Pro M2 Pro]

### ISSUE THREAD

**Issue by Kotov584** [AsahiLinux/asahi-installer#227]
I attempted to install Asahi Fedora Remix but received an error stating that there is insufficient space when there is clearly enough space. I have 335GB of free space, with only about 60GB being used by system shit. 

```bash
Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (494.38 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v14.1 [disk3s3s1, SOME-CODE4
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v14.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s3s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (r): r


We're going to resize this partition:
  APFS [Macintosh HD] (494.38 GB, 6 volumes)
  Total size: 494.38 GB
  Free space: 335.21 GB
  Available space: 0 B
  Overhead: 297.21 GB
  Minimum new size: 494.38 GB (100.00%)

  Warning: The selected partition has a large amount of overhead space.
  This prevents you from resizing the partition to a smaller size, even
  though macOS reports that space as free.

  This is usually caused by APFS snapshots used by Time Machine, which
  use up free disk space and block resizing the partition to a smaller
  size. It can also be caused by having a pending macOS upgrade.

  If you want to resize your partition to a smaller size, please complete
  any pending macOS upgrades and visit this link to learn how to manually
  delete Time Machine snapshots:

    https://alx.sh/tmcleanup

  Not enough available space to resize. Please follow the instructions
  above to continue.
apple@Apples-MacBook-Pro ~ % diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.3 GB   disk0
   1:             Apple_APFS_ISC Container disk1         524.3 MB   disk0s1
   2:                 Apple_APFS Container disk3         494.4 GB   disk0s2
   3:        Apple_APFS_Recovery Container disk2         5.4 GB     disk0s3

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +494.4 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD - Data     142.2 GB   disk3s1
   2:                APFS Volume Macintosh HD            9.9 GB     disk3s3
   3:              APFS Snapshot com.apple.os.update-... 9.9 GB     disk3s3s1
   4:                APFS Volume Preboot                 5.9 GB     disk3s4
   5:                APFS Volume Recovery                1.0 GB     disk3s5
   6:                APFS Volume VM                      20.5 KB    disk3s6
```

**Comment by eslerm** [comment]
`The selected partition has significant disk space overhead.` caught my eye: https://github.com/AsahiLinux/asahi-installer/issues/182

**Comment by marcan** [comment]
The message and linked URL tell you exactly what the problem is. Please read them.

**Comment by Luncheon3462** [comment]
> The message and linked URL tell you exactly what the problem is. Please read them.

@marcan I uninstalled asahi 39 in hopes of installing 40.   Followed instructions to delete partitions in the partitioning cheat sheet.   Got the same message and followed instructions in the URL.   I still get the same message, however.   Here is the output of diskutil list

/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *251.0 GB   disk0
   1:             Apple_APFS_ISC Container disk1         524.3 MB   disk0s1
   2:                 Apple_APFS Container disk3         245.1 GB   disk0s2
   3:        Apple_APFS_Recovery Container disk2         5.4 GB     disk0s3

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +245.1 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD - Data     119.2 GB   disk3s1
   2:                APFS Volume Macintosh HD            10.2 GB    disk3s3
   3:              APFS Snapshot com.apple.os.update-... 10.2 GB    disk3s3s1
   4:                APFS Volume Preboot                 6.2 GB     disk3s4
   5:                APFS Volume Recovery                931.6 MB   disk3s5
   6:                APFS Volume VM                      20.5 KB    disk3s6

/dev/disk4 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                                                   +16.0 TB    disk4

/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +16.0 TB    disk5
                                 Physical Store disk4
   1:                APFS Volume Backups of George’s ... 318.1 GB   disk5s1
