### ISSUE TITLE
Need help with macOS virtual machine on asahi linux

### ISSUE THREAD

**Issue by AlexTrushkovsky** [AsahiLinux/asahi-installer#230]
Good afternoon, everyone. I am having trouble running macos virtual machines on apple sillicon. But if you run them directly on macos, then the functionality of macos vm is limited, namely, the login to apple id does not work (as I understand it, this is deliberately done by apple). So I decided that it might be possible to run a macos virtual machine without restrictions using asahi linux. But unfortunately, I could not find information on how to do this, and whether it is possible at all. I will be very grateful for any thoughts on this matter, and hope that it is possible

**Comment by jannau** [comment]
It is not possible to run graphical macOS arm64 virtual machines under linux and probably never will.
