### ISSUE TITLE
Can't run install script on 2020 M1 Macbook Pro

### ISSUE THREAD

**Issue by BlueRaccoonTech** [AsahiLinux/asahi-installer#232]
I was attempting to run the installer just to confirm I don't have that RecoveryOS issue mentioned under the macOS Sonoma Boot Failures section of the wiki (my Macbook is 13 inch and I was able to get to the boot picker, but I figured the additional test would increase my confidence.)

Upon attempting to run the script, it caught an exception about it being unable to find a SystemRecovery directory and bailed. I do, indeed, lack a SystemRecovery directory under where it was looking - the directory had six folders, five of which were different UUIDs and the sixth was "SFR". If I change the directory mentioned in system.py from SystemRecovery to SFR, it works - but given the SFR directory is explicitly referenced elsewhere in the same script, I've got a feeling this isn't an accurate way of doing things.

I'm running MacOS 14.1.

Below is the full log:
```
10-31 23:56 root         INFO     Startup
10-31 23:56 root         INFO     Environment:
10-31 23:56 root         INFO       INSTALLER_BASE=https://cdn.asahilinux.org/installer
10-31 23:56 root         INFO       INSTALLER_DATA=https://github.com/AsahiLinux/asahi-installer/raw/prod/data/installer_data.json
10-31 23:56 root         INFO       REPO_BASE=https://cdn.asahilinux.org
10-31 23:56 root         INFO       IPSW_BASE=None
10-31 23:56 root         INFO       EXPERT=None
10-31 23:56 root         INFO       REPORT=https://stats.asahilinux.org/report
10-31 23:56 root         INFO       REPORT_TAG=alx-prod
10-31 23:56 root         INFO     Version: v0.6.18
10-31 23:56 root         INFO     MSG: Welcome to the Asahi Linux installer!
10-31 23:56 root         INFO     MSG: This installer will guide you through the process of setting up
10-31 23:56 root         INFO     MSG: Asahi Linux on your Mac.
10-31 23:56 root         INFO     MSG: Please make sure you are familiar with our documentation at:
10-31 23:56 root         INFO     MSG:   https://alx.sh/w
10-31 23:56 root         INFO     MSG: Press enter to continue.
10-31 23:56 root         INFO     MSG: Collecting system information...
10-31 23:56 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1138, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 843, in main
    self.sysinfo = system.SystemInfo()
  File "/private/tmp/asahi-install/system.py", line 8, in __init__
    self.fetch()
  File "/private/tmp/asahi-install/system.py", line 90, in fetch
    for p in os.listdir(base):
FileNotFoundError: [Errno 2] No such file or directory: '/System/Volumes/iSCPreboot/SystemRecovery'
10-31 23:56 root         INFO     MSG: If you need to file a bug report, please attach the log file:
10-31 23:56 root         INFO     MSG:   /private/tmp/asahi-install/installer.log
```

**Comment by clementcohen** [comment]
Hi the same here

**Comment by marcan** [comment]
This should be fixed now. Just to try to get some data on what's going on here, would you mind following these steps?

- Power off the machine
- Do the quick "tap and hold" dance (press, release, press and hold power)
- When the boot picker appears, go into Settings on the right
- Utilities menu → Terminal
- Type `sw_vers`

And report what it prints out. It would be very helpful to figure out if this is a common situation for older versions of System RecoveryOS, or something else.

**Comment by BlueRaccoonTech** [comment]
Here's what I got when I followed those steps:
```
ProductName:    macOS
ProductVersion: 12.3
BuildVersion:   21E230
```

**Comment by clementcohen** [comment]
ProductName: macOS
Productversion: 13.5
BuildVersion: 22G74


Le mer. 1 nov. 2023 à 13:01, Hector Martin ***@***.***> a
écrit :

**Comment by marcan** [comment]
Considering this fixed.
