### ISSUE TITLE
Mismatched System Firmware / System Recovery detected!

### ISSUE THREAD

**Issue by parisni** [AsahiLinux/asahi-installer#239]
Hi
I am running into this issue apparently because

```
Os version: 14.1.1
Main firmware version: 14.1.1
SystemRecovery version: 13.5
```

However I double checked I have promotion enabled (default). 

1. Is there a way to upgrade the system recovery to be equal to bot firmware and os ?
2. Is it safe to force the asahi install in such case ? I am right now not able to understand the risks

maybe @marcan (who wrote the warning)

many thx

**Comment by marcan** [comment]
There is a new workaround in the installer for this now.

**Comment by parisni** [comment]
Yeah I got it working  from https://github.com/AsahiLinux/asahi-installer/commit/f113dc42c9bb7254554e64d94af2ae9d75fa50ee

thanks
