### ISSUE TITLE
No actions available on this system. No partitions have enough free space to be resized, and there is nothing else to be done.

### ISSUE THREAD

**Issue by LucasPeters00** [AsahiLinux/asahi-installer#241]
When I am trying to run the installer I get this error which says there is not enough free space but I have 140 gb free on my MacBook M1 2020. Can this issue be solved or is there as is says nothing to be done? 

'''
Last login: Thu Dec  7 18:49:19 on console
lucaspeters@MBP-van-Lucas ~ % curl https://fedora-asahi-remix.org/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1415  100  1415    0     0  23653      0 --:--:-- --:--:-- --:--:-- 26203

Bootstrapping installer:
  Checking version...
  Version: v0.6.24
  Downloading...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
Password:

Welcome to the Asahi Linux installer!

This installer will guide you through the process of setting up
Asahi Linux on your Mac.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.

Collecting system information...
  Product name: MacBook Pro (13-inch, M1, 2020)
  SoC: Apple M1
  Device class: j293ap
  Product type: MacBookPro17,1
  Board ID: 0x24
  Chip ID: 0x8103
  System firmware: iBoot-10151.41.12
  Boot UUID: 2D8D8BB2-34F1-4178-80B0-99C8E66A8A5E
  Boot VGID: 2D8D8BB2-34F1-4178-80B0-99C8E66A8A5E
  Default boot VGID: 2D8D8BB2-34F1-4178-80B0-99C8E66A8A5E
  Boot mode: macOS
  OS version: 14.1.2 (23B92)
  OS restore version: 23.2.92.0.0,0
  Main firmware version: 14.1.2 (23B92)
  No Fallback System Firmware / rOS
  SFR version: 23.2.92.0.0,0
  SystemRecovery version: 22.7.74.0.0,0 (13.5 22G74)
  Login user: lucaspeters

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (245.11 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v14.1.2 [disk3s1s1, 2D8D8BB2-34F1-4178-80B0-99C8E66A8A5E]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v14.1.2 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1s1) for machine authentication.
No actions available on this system.
No partitions have enough free space to be resized, and there is
nothing else to be done.
'''

**Comment by AeizonJMarks** [comment]
I'm getting this as well. I cannot find any documentation on how to overcome it. How did you install Asashi?
