### ISSUE TITLE
TypeError when running the Asahi Linux Installer v0.7.1

### ISSUE THREAD

**Issue by raw-bin** [AsahiLinux/asahi-installer#246]
Hi.

Hit this when running the installer from 1TR (which I assume is a valid use case).
Please see the attached installer.log for all the details.
Thanks

[asahi-installer.log](https://github.com/AsahiLinux/asahi-installer/files/13742168/asahi-installer.log)

**Comment by raw-bin** [comment]
It appears that `main.sysinfo.sfr_ver` was invalid. I cheated by short-circuiting `run_checks()` in bugs.py which got me a successful installation.

**Comment by alexmyczko** [comment]
@raw-bin ok i have this macbook pro m2 and i want to install debian on it but it fails with

http://sid.ethz.ch/debian/asahi.txt

unfortunately i'm a python illiterate, what exactly do you do with `main.sysinfo.sfr_ver` to get valid? you remove all lines with `run_checks()` and rerun it, that's it?

**Comment by alexmyczko** [comment]
ah someone was fast https://paste.debian.net/hidden/43ecbd58

**Comment by eslerm** [comment]
@alexmyczko Debian Asahi is downstream of Asahi Linux.

You may want to ask for help on https://oftc.irclog.whitequark.org/asahi-alt/ Glanzmann has been active there :)

You may also want to check with https://wiki.debian.org/Teams/Bananas

**Comment by alexmyczko** [comment]
@eslerm 2nd link is from me :) will try 1st

**Comment by eslerm** [comment]
Good to meet you Alex o/

Appreciate all your rust packaging work for Asahi speaker support on Debian and Ubuntu :pray:

**Comment by alexmyczko** [comment]
@eslerm actually I didn't do rust for a lot of time. But I should test that touch graphics thingy once, not getting to it atm... but having two machines and internet helps to get done things. Wait for MiniDebconf Berlin in May...

**Comment by eslerm** [comment]
We should sync, I'm interested in contributing Asahi work to upstream Debian :)

https://github.com/UbuntuAsahi/ubuntu-asahi/issues/99

**Comment by marcan** [comment]
This is fixed in 9cba40dc.
