### ISSUE TITLE
Please enhance foolproofing in the `wipe-linux.sh` script

### ISSUE THREAD

**Issue by rxhfcy** [AsahiLinux/asahi-installer#253]
Today, once again, I witnessed this tragedy happening in the wild (**_not_** the first time i've seen this!):
- someone on the Internet recommended running asahi-installer / tools / `wipe-linux.sh` (https://alx.sh/wipe-linux)
- someone else promptly ignored every warning and lost absolutely everything on their computer, _**including their macOS installation(!)**_
- -> an extremely surprised and angry user who "should have known better" :(
(people who ignore scary warnings probably don't have backups either!)

**Suggestion:**

When running `wipe-linux.sh`, after showing the warnings, force the user to correctly **type in** a sufficiently scary phrase in an input field, before allowing them to continue (to hopefully make them understand that they really are playing with fire).

Something like:
- "Yes, I understand that running this script can destroy my macOS installation and make my computer unbootable!"
...or even:
- "Yes, I want to potentially permanently destroy all of my data (including my current macOS installation) and make my computer unbootable. No, I won't blame anyone else but myself if any of that happens."

Additionally, please use the color **RED** extensively
(bashisms might be bad, but so is destroying other people's data: `echo -e "\e[31mRed Text\e[0m"`)

Also, in the other warning messages, further spell out the danger (be as specific as possible):
- `wipe-linux.sh` might destroy your macOS installation too (it's not just your Linux partitions that are in danger)
- `wipe-linux.sh` might make your computer unbootable

Here's an example from CXPatcher, it's not pretty but it works (screenshot):

<img width="400" alt="CXPatcher screenshot" src="https://github.com/AsahiLinux/asahi-installer/assets/42669366/1ff40265-9ba0-4215-80dc-13154d5b36ee">

**Further attempt to convince you that something must be done to protect newbies from themselves:**

It's impossible to know precisely **_how_** much suffering and monetary loss the script has already caused in the world, but the amount is certainly non-zero. Frankly I think it's irresponsible to publicly host such a dangerous script on the Internet, at least in its current form. The adage “anything that can go wrong will go wrong” applies here. Even if there's only a 1% chance of a catastrophe, that still means that out of every 1000 times wipe-linux.sh is used, there will be 10 **_incredibly_** unhappy customers.

Yes, the script already shows lots of SCARY WARNINGS and forces the user to press enter twice and all, but IMHO that's not nearly enough. Unfortunately, the reality is that users don't read, especially if they are in a hurry, agitated or distracted. This applies doubly to any text displayed on a computer screen. Also, many people will incorrectly assume that only their Linux partitions (**_not macOS_**) are at risk of exploding.

**Comment by marcan** [comment]
If this is about that Reddit guy, I don't think he broke his install using wipe-linux. He was already trying to manually delete his macOS partition (which was failing by pure luck) before even being told to use that script in his original post. Given his abusive replies to other users (again before the wipe-linux thing) he's either an outright troll or has some serious personal issues we can't help with, and he's been banned as a result. I do not consider that incident an issue with wipe-linux.

That said, wipe-linux *is* dangerous (in select situations) and I'm really tired of people linking to that script, so I've removed the shortlink altogether.

**Comment by marcan** [comment]
I'm not aware of any cases of it affecting macOS partitions (under any reasonable situation). If that ever happens, that would be a very interesting bug. The script is dangerous because it indiscriminately erases partitions that "look" like Linux (which could erase non-macOS partitions intended for other purposes, etc.), not because it can make macOS unbootable. As I said, all the system and macOS partitions should never meet the conditions for the script to erase them.

We can't stop people from using dumb scripts. If I delete it from this repo someone will just rehost it elsewhere.
