### ISSUE TITLE
step2.sh enters boot loop.

### ISSUE THREAD

**Issue by IamPyu** [AsahiLinux/asahi-installer#255]
Whenever I try installing Asahi Linux, it enters a boot loop.

I am running on a "13 inch M2 Macbook Pro.

EDIT:

I have tried the following to fix this issue:

- Removing the partitions and trying all over again.
- Restarting my system.
- Updating my system.
- Reinstalling my system.

EDIT:

There is no output before it starts the boot loop so I cannot provide any extra information.

**Comment by IamPyu** [comment]
I wonder what could be going on!

**Comment by IamPyu** [comment]
I don't really understand the commands in the step2.sh script.
I don't really know anything about macOS shell commands or shell script in general.

**Comment by IamPyu** [comment]
Yesterday I tried reinstalling macOS, but that doesn't fix the issue.

**Comment by IamPyu** [comment]
I am trying to install Asahi Linux again, I will reply here if it works.

**Comment by IamPyu** [comment]
step2.sh still does not work.
It continues to trigger bootloops

**Comment by IamPyu** [comment]
I'm going to try and install https://ubuntuasahi.org and see if it works, just to see if this is a problem on just the Fedora Asahi Remix's end.

**Comment by IamPyu** [comment]
Ubuntu Asahi also fails to install, this seems to be an issue on step2.sh's end,

**Comment by eslerm** [comment]
This sounds like an issue on your system. I'd reset by backing-up and reinstalling macOS.

**Comment by IamPyu** [comment]
> This sounds like an issue on your system. I'd reset by backing-up and reinstalling macOS.

I already tried that.

**Comment by eslerm** [comment]
What is the firmware version?

@WeetHet are you also using a 13 inch M2 Macbook Pro? I have the non-pro 13" M2 and do not get the boot loop.

**Comment by IamPyu** [comment]
I have the 13 inch M2 Macbook Pro as stated in the issue description.

**Comment by WeetHet** [comment]
> What is the firmware version?
> 
> @WeetHet are you also using a 13 inch M2 Macbook Pro? I have the non-pro 13" M2 and do not get the boot loop.

No, I have 13 inch MacBook Pro with M1

**Comment by IamPyu** [comment]
Just some extra information, the boot loop happens after the first password prompt.

**Comment by marcan** [comment]
Boot into recoveryOS (Startup Options), pull up a terminal (it's in the menu), and run `curl -L https://alx.sh/cleanbp | sh`. Then try again.

This is an Apple bug that happens when you've installed an OS too many times.

If that doesn't work, please run the Asahi installer and paste the entire system info section.

**Comment by IamPyu** [comment]
> @IamPyu:
> 
> > Just some extra information, the boot loop happens after the first password prompt.
> 
> BTW did you use the correct username? (You're supposed to use whatever `whoami` normally reports for you in macOS `Terminal.app`)

Yes I did.

**Comment by WeetHet** [comment]
> Boot into recoveryOS (Startup Options), pull up a terminal (it's in the menu), and run `curl -L https://alx.sh/cleanbp | sh`. Then try again.
> 
> This is an Apple bug that happens when you've installed an OS too many times.
> 
> If that doesn't work, please run the Asahi installer and paste the entire system info section.

Thanks, that fixed it!

**Comment by IamPyu** [comment]
> Boot into recoveryOS (Startup Options), pull up a terminal (it's in the menu), and run `curl -L https://alx.sh/cleanbp | sh`. Then try again.
> 
> This is an Apple bug that happens when you've installed an OS too many times.
> 
> If that doesn't work, please run the Asahi installer and paste the entire system info section.

Thank you!

**Comment by tungmv** [comment]
I facing the same issue as describe before, but the solution @marcan gave doesn't work for me. Here is my system info when I run the script. Also, I tried the 'p' option to repair partition but the script still print out 'incomplete install'. Thank you

```
Collecting system information...
  Product name: MacBook Air (M2, 2022)
  SoC: Apple M2
  Device class: j413ap
  Product type: Mac14,2
  Board ID: 0x28
  Chip ID: 0x8112
  System firmware: iBoot-11881.41.5
  Boot UUID: AAE9B598-E0D4-494B-9F7A-E4DA6F095783
  Boot VGID: AAE9B598-E0D4-494B-9F7A-E4DA6F095783
  Default boot VGID: A17EF637-1F17-43F3-B53E-96AB0CD97407
  Boot mode: macOS
  OS version: 14.7.1 (23H222)
  OS restore version: 23.8.222.0.0,0
  Main firmware version: 15.1.1 (24B91)
  No Fallback System Firmware / rOS
  SFR version: 24.2.91.0.0,0
  SystemRecovery version: 23.7.93.0.0,0 (14.6.1 23G93)
  Login user: tony

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (86.79 GB, 6 volumes)
    OS: [B ] [Macintosh HD] macOS v14.7.1 [disk4s1s1, AAE9B598-E0D4-494B-9F7A-E4DA6F095783]
  2: APFS [ASAHI] (2.50 GB, 4 volumes)
    OS: [ *] [ASAHI] incomplete install (macOS 13.5 stub) [disk2s2, A17EF637-1F17-43F3-B53E-96AB0CD97407]
  3: EFI (524.29 MB)
  4: Linux Filesystem (1.07 GB)
  5: Linux Filesystem (154.22 GB)
  6: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v15.1.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume
```

**Comment by tungmv** [comment]
Sorry for the inconvenience. I have fixed the issue by not accessing the 1TR mode (which requires pressing the power button twice) and instead using the Recovery OS in Asahi Linux (which requires a single press).
