### ISSUE TITLE
bro what am i supposed to do

### ISSUE THREAD

**Issue by hqc8848** [AsahiLinux/asahi-installer#259]
I can't install Asahi linux
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/14622397/installer.log)
Bro what am I supposed to do

**Comment by unsunsk8er** [comment]
I can't install it too in my M1 Macbook Air (Sonoma 14.4)
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/14622890/installer.log)

**Comment by hqc8848** [comment]
my Mac is MacBook Pro 2022 M2 with macOS Sonoma 14.4

**Comment by jKaarlehto** [comment]
to get started

brew install llvm
git clone --recursive https://github.com/AsahiLinux/asahi-installer
chmod +x ./build.sh
/.build.sh

**Comment by hqc8848** [comment]
> to get started
> 
> ```
> brew install make
> brew install llvm
> git clone --recursive https://github.com/AsahiLinux/asahi-installer
> chmod +x ./build.sh
> ./build.sh
> ```

same thing happening
```
Building m1n1...
INFO: Building on Darwin
INFO: Toolchain path: /opt/homebrew/opt/llvm/bin/
  IMG   build/bootlogo_128.bin
  IMG   build/bootlogo_256.bin
  CP    build/font.bin
  CP    build/font_retina.bin
  RS    build/librust.a
  CC FP build/math/expf.o
  CC FP build/kboot_gpu.o
make: cargo: No such file or directory
make: *** [build/librust.a] Error 1
make: *** Waiting for unfinished jobs....
rm build/bootlogo_128.bin build/bootlogo_256.bin build/font.bin build/font_retina.bin
```
HOW?

**Comment by neofright** [comment]
You could try installing `rust`.
e.g.
`$ brew install rust`

as it seems you're missing `cargo`:
`make: cargo: No such file or directory`

**Comment by fengdi** [comment]
I can't install it too in my M1 Macbook Air (Sonoma 14.4 and Ventura 13.6.5)

**Comment by hqc8848** [comment]
> You could try installing `rust`. e.g. `$ brew install rust`
> 
> as it seems you're missing `cargo`: `make: cargo: No such file or directory`

thx but...

```
Building m1n1...
INFO: Building on Darwin
INFO: Toolchain path: /opt/homebrew/opt/llvm/bin/
  RS    build/librust.a
   Compiling memchr v2.4.1 (/Users/heiqingcai/asahi-installer/m1n1/rust/vendor/memchr)
   Compiling cfg-if v1.0.0 (/Users/heiqingcai/asahi-installer/m1n1/rust/vendor/cfg-if)
   Compiling cty v0.2.2 (/Users/heiqingcai/asahi-installer/m1n1/rust/vendor/cty)
   Compiling log v0.4.17 (/Users/heiqingcai/asahi-installer/m1n1/rust/vendor/log)
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-unknown-none-softfloat` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-unknown-none-softfloat`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `compiler_builtins`

error: unused import: `pwd::*`
  --> vendor/cty/src/lib.rs:17:9
   |
17 | pub use pwd::*;
   |         ^^^^^^
   |
note: the lint level is defined here
  --> vendor/cty/src/lib.rs:9:9
   |
9  | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(unused_imports)]` implied by `#[deny(warnings)]`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
libunwind: malformed __unwind_info at 0x189020CA8 bad second level page
error: could not compile `cty` (lib) due to 3 previous errors
make: *** [build/librust.a] Error 101
```

**Comment by ivabus** [comment]
> ```
>   = note: the `aarch64-unknown-none-softfloat` target may not be installed
>   = help: consider downloading the target with `rustup target add aarch64-unknown-none-softfloat`
>   = help: consider building the standard library from source with `cargo build -Zbuild-std`
> ```

**Comment by hqc8848** [comment]
> rustup target add aarch64-unknown-none-softfloat

umm how to use rustup command

**Comment by ivabus** [comment]
wait, looking at your first command, it seems like your mac lost connection to the internet (or asahi, or apple servers) during the installation, try to install AsahiLinux with a stable internet connection

**Comment by ivabus** [comment]
Maybe something breaks your connection with the server during the installation. Installer needs to download ~5GB of data during the installation

**Comment by hqc8848** [comment]
Now that I think about it, macOS works
