### ISSUE TITLE
- root        : ERROR    Exception caught while installing Fedora Asahi Remix 39 with KDE Plasma

### ISSUE THREAD

**Issue by adistrim** [AsahiLinux/asahi-installer#262]
I have tried to install it multiple times and even tried GNOME also but the issue is the same I have installed Asahi before but never got this error.

<img width="1440" alt="Screenshot 2024-03-29 at 22 50 40" src="https://github.com/AsahiLinux/asahi-installer/assets/98259698/caaa1841-811b-423a-a91b-a213123bd06e">

**Comment by adistrim** [comment]
here's the installer.log attached

[installer.log](https://github.com/AsahiLinux/asahi-installer/files/14807037/installer.log)

**Comment by marcan** [comment]
Did this happen once or does it reproduce? As far as I can tell this can only happen if the server returns no data, so it could be a network issue.

**Comment by adistrim** [comment]
Hi marcan, I tried to install it again in April (after a week) and it worked. I think it was a network issue.
