### ISSUE TITLE
Your system did not boot into the correct recovery

### ISSUE THREAD

**Issue by cskn95** [AsahiLinux/asahi-installer#263]
I did everything exactly but stuck on step 2. It says "Your system did not boot into the correct recovery" and wants my login informations for a fix but that does not work too. 

https://drive.google.com/file/d/1T_Aa1w6bMPi_UP186vao9IGalrwQDRN1/view?usp=sharing

**Comment by marcan** [comment]
The link is dead.

**Comment by LKNSI** [comment]
Same here.

Latest macos (latest)
MBP 16" M1 pro, 2021.

All went smoothly, but returns "Your system did not boot into the correct recoveryOS"

Fedora w/ KDE

**Comment by marcan** [comment]
You probably accidentally double-tapped the power button instead of single press and hold. That gets you into System RecoveryOS which is the wrong recoveryOS (you need the Paired RecoveryOS).

**Comment by cskn95** [comment]
Sorry for my bad English, I'm not native. When you said push and hold I thought I should double tap and hold on the second press. In Turkish we talk like that at least. Sorry again.
