### ISSUE TITLE
Asahi Linux installer failure (alternative distro Debian)

### ISSUE THREAD

**Issue by sebastienMLS** [AsahiLinux/asahi-installer#264]
Hello,

Please find the installer.log file attached to this message. It reports a failure during the installation process.

[installer.log](https://github.com/AsahiLinux/asahi-installer/files/14937104/installer.log)

Thanks a lot for your work.
Sébastien

**Comment by eslerm** [comment]
This repo is for upstream Asahi Linux. You would need to ask Thomas Glanzmann for support for his Debian installer.

Please note that Glanzmann's Debian installer is separate from the Debian Bananas who are working on official Asahi Debian support: https://wiki.debian.org/Teams/Bananas

**Comment by sebastienMLS** [comment]
Hello,
Sorry for that. I followed Thomas Glanzmann instructions. I will check with him.
Thank you for the note.
Good evening.
