### ISSUE TITLE
Hard to install in China

### ISSUE THREAD

**Issue by hqc8848** [AsahiLinux/asahi-installer#266]
It's *very super ultra hard* to install it in China
I think I found it on **Tsinghua Mirror** but *(sign)* it's damn archlinux
***SOMEONE COME HELP ME PLEASE! ! !***

**Comment by Nikolaidp24** [comment]
> It's _very super ultra hard_ to install it in China I think I found it on **Tsinghua Mirror** but _(sign)_ it's damn archlinux _**SOMEONE COME HELP ME PLEASE! ! !**_

Are you using a VPN?

**Comment by hqc8848** [comment]
> > It's _very super ultra hard_ to install it in China I think I found it on **Tsinghua Mirror** but _(sign)_ it's damn archlinux _**SOMEONE COME HELP ME PLEASE! ! !**_
> 
> Are you using a VPN?

Nope, it's *too expensive*

**Comment by hqc8848** [comment]
> > It's _very super ultra hard_ to install it in China I think I found it on **Tsinghua Mirror** but _(sign)_ it's damn archlinux _**SOMEONE COME HELP ME PLEASE! ! !**_
> 
> Are you using a VPN?

Well I log in Github with Tor Browser and Steam++

**Comment by v-Ys** [comment]
> Nope, it's _too expensive_

You should consider contacting mirror sites or purchasing a VPN. Providing legal online services to China is difficult and cumbersome for foreigners, with costs much higher than purchasing a VPN. VPNs are not expensive, around ¥15 per month. Please search for more relevant information on Google.

**Comment by hqc8848** [comment]
Well I'm just **Grade Five**, expensive means *I can't even pay*.
By the way you ***still*** need a VPN to visit Google in China

**Comment by v-Ys** [comment]
Ask your parents for it;I believe they will support you.

**Comment by hqc8848** [comment]
I found a VPN called *Windscribe*, but now I can't connect to Tor Network
I'll just try later ;)

**Comment by marcan** [comment]
Sorry, there is no reasonable way for us to bypass China's ever-shifting government censorship. Chinese users are welcome to come up with their own workarounds (VPNs, mirrors, etc.) but it's not something we can take upon ourselves.

**Comment by hqc8848** [comment]
Oh, thanks :)

**Comment by runxiyu** [comment]
My method (while, as far as I know, remaining completely legal) is to download the zip onto a VPS, host it with a nginx (any web server that accepts byte ranges should work), change the URL in installer_data.json to the URL on my VPS, and install from there

Occasionally I still run into issues downloading things other than the main OS zip archive but most of the time the above works
