### ISSUE TITLE
Failed to run bless

### ISSUE THREAD

**Issue by CubeOfCheese** [AsahiLinux/asahi-installer#267]
On Macbook Pro 13 inch M1 2020

Trying to install Asahi Linux Fedora with Gnome

```
Setting the new OS as the default boot volume...
Bootability failed Error Domain=BYErrorDomain Code=103 "Owner authentication is required" UserInfo={BYErrorHint=LocalAuthenticationRequired, NSLocalizedDescription=Owner authentication is required}
Failed to run bless. Press enter to try again.
```

It won't accept my password. I am doing this on an admin account and I removed admin privileges from the original admin because I thought that would force my account to become the "owner" but maybe I misunderstand what owner means in this context.

[installer.log](https://github.com/AsahiLinux/asahi-installer/files/15050019/installer.log)

**Comment by marcan** [comment]
macOS works in mysterious ways... it sounds like your admin account is not, in fact, a machine owner. Unfortunately I have no idea how you control what accounts are machine owners in macOS or how to even find out :/ (I think it *should* be every admin user but...)

One thing you can try is `sudo diskutil apfs updatePreboot /` and try again. If it works after that, looks like your Preboot volume data was out of date.

**Comment by marcan** [comment]
This is probably fixed in the latest version.
