### ISSUE TITLE
IAPhysicalMedia.plist version

### ISSUE THREAD

**Issue by zzywysm** [AsahiLinux/asahi-installer#280]
In src/step2/IAPhysicalMedia.plist the listed version is still 12.1, a remnant from the very first Asahi Linux releases.

Should this be updated to 13.5?

**Comment by marcan** [comment]
Probably doesn't matter? Feel free to file a PR though.

**Comment by jannau** [comment]
please test if installing `12.3` is still after bumping it to to 13.5. I wouldn't bother updating it while it causes no issues.
