### ISSUE TITLE
feature: add customized Volume Icons to Asahi created volumes

### ISSUE THREAD

**Issue by PaulCharlton** [AsahiLinux/asahi-installer#293]
feature: add customized Volume Icons to Asahi created volumes

This can be done by providing an appropriate hidden file named `.VolumeIcon.icns` at the root of the primary volume

**Comment by PaulCharlton** [comment]
WIP: still triaging -- the installer is dropping a `.VolumeIcon.icns` file on the `Fedora` APFS volume, but not on the `Fedora - Data` APFS Volume

**Comment by marcan** [comment]
This already works, it's how the Boot Picker icons get set.
