### ISSUE TITLE
feature: do not show Asahi volumes in macOS finder

### ISSUE THREAD

**Issue by PaulCharlton** [AsahiLinux/asahi-installer#294]
feature: do not show Asahi volumes in macOS finder, and: do not mount them by default

After installing Asahi, the APFS system volume created by Asahi shows up in Finder and is default mounted on macOS in /Volumes, likewise
the APFS data volume created by Asahi DOES not show up in Finder, but is still mounted at /Volumes.

**Comment by PaulCharlton** [comment]
PR forthcoming

**Comment by PaulCharlton** [comment]
`sudo touch /Volumes/YourVolume/.metadata_never_index`

`sudo diskutil mount -mountOptions nobrowse /dev/diskXsY`

`sudo chflags hidden /Volumes/asahiVolume`

**Comment by marcan** [comment]
No modifying fstab. See #306.
