### ISSUE TITLE
feature: affirmatively label each Asahi created APFS volume

### ISSUE THREAD

**Issue by PaulCharlton** [AsahiLinux/asahi-installer#295]
feature: affirmatively label each Asahi created APFS volume

this could be accomplished by `touch /.asahiVolume` at install time when the Volume is mounted.   This can also apply to the ESP.

Helpful for later uninstall or other housekeeping tasks.

**Comment by PaulCharlton** [comment]
PR forthcoming

**Comment by marcan** [comment]
`osenum.py` already has a way of identifying what is a stub and what isn't.
