### ISSUE TITLE
feature: drop a volume and partition manifest in the Asahi APFS system volume

### ISSUE THREAD

**Issue by PaulCharlton** [AsahiLinux/asahi-installer#296]
feature: drop a volume and partition manifest in the Asahi APFS system volume

preferably a json or yaml file containing partition `/dev/diskNsN` could be dropped into the Asahi APFS system volume at something like `/.AsahiStorageManifest`

This will help with uninstalling without hokey heuristics and help avoid damage to partitions not intended to be managed by Asahi lifecycle and related housekeeping.

The partition subtree in `installer_data.json` is a good start, and perhaps these could be conformed with each other.

Also helps with affirmative removal of Asahi related entries from the `iBootSystemContainer` when Asahi is uninstalled

**Comment by PaulCharlton** [comment]
also helps when there are multiple installations of Asahi on the same Mac hardware.

**Comment by marcan** [comment]
> This will help with uninstalling without hokey heuristics and help avoid damage to partitions not intended to be managed by Asahi lifecycle and related housekeeping.

The heuristics are necessary once we support installing with customizable storage layouts via a ramdisk installer boot, since at that point the installer will not be aware of the eventual disk layout since that process complete.
