### ISSUE TITLE
bug: fix: ignore the contents of ./releases folder

### ISSUE THREAD

**Issue by PaulCharlton** [AsahiLinux/asahi-installer#298]
bug: fix: ignore the contents of ./releases folder

The `releases` folder is currently pinned for `git` with a `.keep` file.

However, after a full build, all other files in the `releases` folder are being scanned by `git` as "untracked"

add an entry to `.gitignore` which preserves the `.keep` but ignores all visible files.   ie: `releases/*` since the globbing does not include hidden files by default

**Comment by marcan** [comment]
No. Did you even test this? The release files are `.tar.gz` files and there is a `*.tar.gz` in the `.gitignore`, therefore those files don't show up as untracked. If you are dumping other stuff in `releases` yourself that's your problem.
