### ISSUE TITLE
Builds broken on macOS

### ISSUE THREAD

**Issue by blacktop** [AsahiLinux/asahi-installer#3]
lineno 48

`7z x -so "$DL/$PYTHON_PKG" Python_Framework.pkg/Payload | zcat | \
    cpio -i -D "$PACKAGE/Frameworks/Python.framework"`

```bash
Extracting Python framework...
Brief Usage:
  List:    cpio -it < archive
  Extract: cpio -i < archive
  Create:  cpio -o < filenames > archive
  Help:    cpio --help
```

**Comment by blacktop** [comment]
Building on M1 mac w/ `USE_CLANG=1`

**Comment by marcan** [comment]
We don't really support builds under macOS. There is instead a `test.sh` these days that you can use to run the installer directly, as long as you have Python3 installed.
