### ISSUE TITLE
feature: create homebrew wrapper for Asahi instance lifecycle

### ISSUE THREAD

**Issue by PaulCharlton** [AsahiLinux/asahi-installer#303]
feature: create homebrew wrapper for Asahi instance lifecycle

Would look something like this:

brew install asahi

brew uninstall asahi

brew upgrade asahi

and then:

asahi install [ physical_disk_device_identifier ] [--os OS_URL] [--fs [zfs|btrfs|ext4]

asahi remove [ asahi_esp_partition_device_identifier ]

asahi upgrade [ asahi_esp_partition_device_identifier ]

Benefits: package manager is familiar to most sophisticated macOS users and can manage all dependencies of the asahi lifecycle management tools,  The asahi instance lifeyccle management tools installed this way can also drop some shell completion scripts to prompt the user to with the option parameters

Related:
1) make asahi instance lifecycle management tools into a single command available on macOS
2) add a `man` page for asahi instance lifecycle management tools

**Comment by PaulCharlton** [comment]
PR forthcoming

**Comment by marcan** [comment]
No.
