### ISSUE TITLE
feature: leave macOS as default boot until Asahi LSP is created

### ISSUE THREAD

**Issue by PaulCharlton** [AsahiLinux/asahi-installer#305]
feature: leave macOS as default boot until Asahi LSP is created

See discussion in #304.   The current installer does not produce a system that default boots [short press power button] to Asahi until after the Asahi LSP is created in the Asahi-paired `Recovery Console`.

The chicken-egg issue is that the user can not get to the Asahi-paired `Recovery Console` without a [long press power button], so what happens when the user does a [short press power button] in this interim state of partial install?

The fundamental question is what is the most graceful way to have the user authorize creation of the Asahi LSP, and how does the user get to the Asahi-paired `Recovery Console`.

This "issue" advocates:
1) leaving the macOS as the default boot until the user does the long-press-power boot and can access the Asahi-paired `Recovery Console` from there
2) once the Asahi-paired `Recovery Console` creates the LSP, we can, as part of that process, set Asahi as the default boot option.

related: #304

**Comment by PaulCharlton** [comment]
PR forthcoming

**Comment by marcan** [comment]
(See comment on #304)
