### ISSUE TITLE
Hard to install in China

### ISSUE THREAD

**Issue by HUlele-hub** [AsahiLinux/asahi-installer#327]
I am a 13-year-old Chinese student. So please forgive me for any grammatical errors.
I used a VPN-like software called ‘Steam++’ to access Github, but at the last stage of installation the installer needs to visit a website called ‘asahilinux-fedora.b-cdn.net’ to download ‘’. ‘to download ‘https://asahilinux-fedora.b-cdn.net/os/fedora-40-gnome-202405221600.zip’, but I don't have any way to access this site from China (unless I use a VPN, which is expensive and my parents wouldn't give me any money), so could you please move this file to Github?
<img width="1710" alt="截屏2024-08-29 17 37 08" src="https://github.com/user-attachments/assets/99895ce2-ac21-4ec4-996e-88c7b2b15a60">

**Comment by eslerm** [comment]
Please note https://github.com/AsahiLinux/asahi-installer/issues/68

**Comment by HUlele-hub** [comment]
#68 says he can't access github, but I can. What I can't access is ‘asahilinux-fedora.b-cdn.net’ which there is no way to access with steam++ help.You don't need to do anything illegal like mentioned in #68. Just let us use GitHub to finish the installation. If you can't do that,  I'll try something else.
