### ISSUE TITLE
Installation fails with bless error

### ISSUE THREAD

**Issue by benjamineskola** [AsahiLinux/asahi-installer#328]
2020 M1 Macbook Pro running MacOS Sequoia 15.0. Running the installer from alx.sh runs smoothly up until what I assume is the final stage of marking the partition as bootable, at which point the bless command fails:

```
Bootability failed Error Domain=BYErrorDomain Code=410 "Failed to create paired recovery local policy" UserInfo={NSLocalizedDescription=Failed to create paired recovery local policy, NSUnderlyingError=0x600001ba8060 {Error Domain=com.apple.bootpolicy Code=6 "image4 (6)" UserInfo={NSLocalizedDescription=image4 (6)}}}
```

Rebooting and manually selecting the Fedora partition to boot from then takes me to the recovery console instead. Re-running the Asahi installer again (either from recovery or from a normal macos boot) shows the installation as incomplete, offers the option to complete the installation, but fails in the same way.

Running the bless command manually also produces the same error. The Fedora and Debian versions of the installer also failed in the same way (probably obviously, but I thought it was worth a try).

**Comment by sap-nocops** [comment]
I have the same on 2020 Macbook Pro M1 Sonoma 14.6.1 (23G93)

**Comment by f1sherb0y** [comment]
Same error on 2020 Macbook Pro M! Sonoma 14.6.1 (239G3)

**Comment by maxlei100130** [comment]
1

**Comment by catcombo** [comment]
Have the same issue on Mac mini M1 running under MacOS Sonoma.

**Comment by benjamineskola** [comment]
This now works for me (installer version 0.7.7, tested yesterday, 28 Nov.) — the fix seems to relate to rebooting into recovery mode to do the marking as bootable. (I'm not sure if that was a change in this repository or some other part of asahi.)
