### ISSUE TITLE
Bug while installing Asahi Linux

### ISSUE THREAD

**Issue by HugoBubble** [AsahiLinux/asahi-installer#338]
I got a bug while installing Asahi using command "curl https://alx.sh | sh"
[installer.log](https://github.com/user-attachments/files/17608159/installer.log)

---- 

<img width="932" alt="Screenshot 2024-11-02 at 10 51 55 PM" src="https://github.com/user-attachments/assets/d65db76e-562b-4a23-a721-edfb9533686b">

**Comment by HugoBubble** [comment]
this is info for my device:
  Product name: MacBook Pro (13-inch, M1, 2020)
  SoC: Apple M1
  Device class: j293ap
  Product type: MacBookPro17,1
  Board ID: 0x24
  Chip ID: 0x8103
  System firmware: iBoot-11881.41.5
  Boot UUID: AD1CC393-7673-453E-8127-79AC99DFD65D
  Boot VGID: AD1CC393-7673-453E-8127-79AC99DFD65D
  Default boot VGID: AD1CC393-7673-453E-8127-79AC99DFD65D
  Boot mode: macOS
  OS version: 15.1 (24B83)
  OS restore version: 24.2.83.0.0,0
  Main firmware version: 15.1 (24B83)
  No Fallback System Firmware / rOS
  SFR version: 24.2.83.0.0,0
  SystemRecovery version: 23.7.93.0.0,0 (14.6.1 23G93)
  Login user: cupcake

**Comment by saifulapm** [comment]
I am getting same problem..
