### ISSUE TITLE
Preboot folder file doesn't exist

### ISSUE THREAD

**Issue by dhs17y2adonchia** [AsahiLinux/asahi-installer#38]
Hardware:
MacBook Pro (13-inch, M1, 2020)
16GB Memory
1TB SSD

Issue:
```bash
Preboot folder path "/Volumes/Preboot/2619E52E-F53F-4CB9-8116-25F15BDCA26B/System/Library/CoreServices" doesn't exist.
Couldn't set bless data in preboot volume for device /dev/disk4s2
Failed to run bless. Press enter to try again.
```

Everything was going smoothly till this step. Poked around said folder and found that System/Library/CoreServices were all missing within the folder, everything else seems to have installed smoothly.

**Comment by marcan** [comment]
That's weird; those folders aren't supposed to exist, at least the way we set up these partitions. They aren't required as far as I can tell. I think I remember that error from old `bless` versions pre 12.3, which could only handle Intel macs, but I've never seen it on Apple Silicon. That folder only contains the Intel EFI booter...

Can you run some diagnostic commands?

```
bless --version
diskutil list
sw_vers
find /Volumes/Preboot > preboot.txt
```

Paste in the output and please also attach preboot.txt.

Then you can try this: `bless --setBoot --device /dev/disk4s2`

It should error out the same way. And then, just for kicks, try making those folders and the dummy booter and try again:
```
mkdir -p /Volumes/Preboot/2619E52E-F53F-4CB9-8116-25F15BDCA26B/System/Library/CoreServices
touch /Volumes/Preboot/2619E52E-F53F-4CB9-8116-25F15BDCA26B/System/Library/CoreServices/boot.efi
bless --setBoot --device /dev/disk4s2
```

If that works, follow the rest of the installation instructions (shut down your system, power up holding down the power button, select Asahi, then follow the prompts). I have no idea why boot.efi would be required for you though... but if this works maybe we should just do that for everyone.

**Comment by dhs17y2adonchia** [comment]
Thanks for the reply! I'll give it a shot again and will post my results here in a bit 👍🏻

**Comment by marcan** [comment]
Wait, I had a hunch. Ha!

Do you have Terminal.app configured to run under Rosetta?

`bless` tries to do the x86 thing if you run it as an x86 app :-)

**Comment by dhs17y2adonchia** [comment]
Oh! I think you might be right! I do indeed have Rosetta enabled for the terminal, had it like this due to me installing Homebrew early in the M1's lifecycle. Let me retry this with rosetta unchecked.

**Comment by marcan** [comment]
Should be fixed in 3738ea119 / v0.3.9 (not pushed to production yet)

**Comment by marcan** [comment]
Now live!

**Comment by dhs17y2adonchia** [comment]
You are amazing my dude! I'll try installing from the latest version right now, will update!

**Comment by marcan** [comment]
Make sure you delete your existing partitions first if you're doing a full reinstall. You can use this:

```
sudo -i
curl -L https://alx.sh/wipe-linux | sh
```

(You can ignore "operation not permitted" errors at the end)

**Comment by dhs17y2adonchia** [comment]
<img width="1280" alt="Screenshot_20220320_164226" src="https://user-images.githubusercontent.com/24926784/159154828-ceb54a2a-a229-4f31-bf14-2c0370b31a09.png">

Success! Thank you so much for the hard work, really appreciate your replies as well!
