### ISSUE TITLE
Failure to add APFS volume

### ISSUE THREAD

**Issue by dottedmag** [AsahiLinux/asahi-installer#42]
```
Preparing target volumes...
Failed to run process: diskutil quiet apfs addVolume disk4 apfs 'Asahi Linux' -role S -groupWith disk4s1
Output: b'Will export new APFS Volume "Asahi Linux" from APFS Container Reference disk4\n'
root        : ERROR    Process execution failed
```

See the attached log
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/8310944/installer.log)

I'm not touching this machine in case further investigation is needed.

**Comment by dottedmag** [comment]
Same problem, from IRC:

> <mattebullet[m]> I had a small problem with the first run of the install script that I wanted to report. It failed while preparing target volumes on a diskutil command. I run it a second time and the second time it worked. https://pastebin.com/8Xy3wbWR

**Comment by marcan** [comment]
Unfortunately the installer at that point didn't have enough logging to figure out what happened here :(

It does now, so hopefully the next time someone runs into it we'll have more information.

**Comment by dottedmag** [comment]
Does not seem to happen the second time around, like `mattebullet[m]` observed.

**Comment by marcan** [comment]
I think this is a diskutil race/bug that is worked around now, please reopen if it happens again.
