### ISSUE TITLE
How to replace current asahilinux paritition

### ISSUE THREAD

**Issue by Inc0n** [AsahiLinux/asahi-installer#46]
I chose to install minimal initially, only to realise there won't be network setup, easily.

As I tried to install asahilinux again, it doesn't support replace a current installation at the moment. 

Bootstrap installer Version: v0.3.10

It would be very helpful if this can be realised.

Thank you

**Comment by marcan** [comment]
This was a bit of a documentation mishap; we actually set up `iwd` in the minimal install for this. You can use `systemctl start iwd` and then `iwctl` to connect to wifi, and possibly `dhcpcd` to get an IP.

For wiping the existing install, I'll add something to the installer soon, but for now there is a hacky script you can run:

```
sudo -i
curl -L https://alx.sh/wipe-linux | sh
```

Please only do this if you only have one or several large macOS partitions and you want to delete everything else. It'll indiscriminately remote any 2.5GB APFS partitions and any non-APFS partitions mentioning "EFI" "asahi" or "linux" in the name. If in doubt download the script and run the diskutil commands manually. Also, you can ignore operation not permitted errors at the end, that's part of the Boot Policy cleanup which isn't strictly required unless you reinstall many times.

**Comment by Inc0n** [comment]
This is very helpful thanks!
