### ISSUE TITLE
extracting root.img frozen . Please help me to clean the created partitions 

### ISSUE THREAD

**Issue by Mraghuvaran** [AsahiLinux/asahi-installer#49]
curl https://alx.sh | sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   967  100   967    0     0    548      0  0:00:01  0:00:01 --:--:--   550

Bootstrapping installer:
  Checking version...
  Version: v0.3.9
  Downloading...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
Password:

Welcome to the Asahi Linux installer!

This installer is in an alpha state, and may not work for everyone.
It is intended for developers and early adopters who are comfortable
debugging issues or providing detailed bug reports.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.

By default, this installer will hide certain advanced options that
are only useful for developers. You can enable expert mode to show them.
» Enable expert mode? (y/N): N

Collecting system information...
  Product name: MacBook Air (M1, 2020)
  SoC: Apple M1
  Device class: j313ap
  Product type: MacBookAir10,1
  Board ID: 0x26
  Chip ID: 0x8103
  System firmware: iBoot-7459.101.2
  Boot UUID: F2577686-35E3-46E4-BBDA-2D744A0E0D20
  Boot VGID: F2577686-35E3-46E4-BBDA-2D744A0E0D20
  Default boot VGID: F2577686-35E3-46E4-BBDA-2D744A0E0D20
  Boot mode: macOS
  OS version: 12.3 (21E230)
  System rOS version: 12.3 (21E230)
  No Fallback rOS
  Login user: raghu

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (245.11 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v12.3 [disk3s1, F2577686-35E3-46E4-BBDA-2D744A0E0D20]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v12.3 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (r): r

We're going to resize this partition:
  APFS [Macintosh HD] (245.11 GB, 6 volumes)
  Total size: 245.11 GB
  Free space: 90.43 GB
  Minimum free space: 38.00 GB
  Minimum total size: 192.68 GB (78.61%)

Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (min): 35GB
Size is too small, please enter a value > 192.68 GB (78.61%)
» New size (min): min 

Resizing will free up 52.43 GB of space.

Note: your system may appear to freeze during the resize.
This is normal, just wait until the process completes.
» Continue? (y/N): y

Started APFS operation
Aligning shrink delta to 52,429,258,752 bytes and targeting a new physical store size of 192,677,937,152 bytes
Determined the minimum size for the targeted physical store of this APFS Container to be 158,611,800,064 bytes
Resizing APFS Container designated by APFS Container Reference disk3
The specific APFS Physical Store being resized is disk0s2
Verifying storage system
Using live mode
Performing fsck_apfs -n -x -l /dev/disk0s2
Checking the container superblock
Checking the EFI jumpstart record
Checking the space manager
Checking the space manager free queue trees
Checking the object map
Checking the encryption key structures
Checking volume /dev/rdisk3s1
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking snapshot 1 of 1 (com.apple.os.update-2289385E1A6FCCF05D444673FB1FEB06DDCF82A4C723EAD53AF1F3E08872CE0F)
Checking the fsroot tree
Checking the file extent tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s1 appears to be OK
Checking volume /dev/rdisk3s2
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s2 appears to be OK
Checking volume /dev/rdisk3s3
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s3 appears to be OK
Checking volume /dev/rdisk3s4
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s4 appears to be OK
Checking volume /dev/rdisk3s5
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the document ID tree
Checking the fsroot tree
Checking the extent ref tree
Checking the file key rolling tree
Verifying volume object map space
The volume /dev/rdisk3s5 appears to be OK
Checking volume /dev/rdisk3s6
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s6 appears to be OK
Verifying allocated space
The container /dev/disk0s2 appears to be OK
Storage system check exit code is 0
Shrinking APFS Physical Store disk0s2 from 245,107,195,904 to 192,677,937,152 bytes
Shrinking APFS data structures
Shrinking partition
Modifying partition map
Finished APFS operation

Resize complete. Press enter to continue.

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (192.68 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v12.3 [disk3s1, F2577686-35E3-46E4-BBDA-2D744A0E0D20]
  2: (free space: 52.43 GB)
  3: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v12.3 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1) for machine authentication.

Choose what to do:
  f: Install an OS into free space
  q: Quit without doing anything
» Action (f): f

Choose an OS to install:
  1: Asahi Linux Desktop
  2: Asahi Linux Minimal (Arch Linux ARM)
  3: UEFI environment only (m1n1 + U-Boot + ESP)
» OS: 1

Downloading OS package info...
.

Minimum required space for this OS: 15.00 GB

Available free space: 52.43 GB

How much space should be allocated to the new OS?
  You can enter a size such as '1GB', a fraction such as '50%',
  the word 'min' for the smallest allowable size, or
  the word 'max' to use all available space.
» New OS size (max): 35GB

The new OS will be allocated 35.00 GB of space,
leaving 17.43 GB of free space.

Enter a name for your OS
» OS name (Asahi Linux): LinuxM1

Using macOS 12.3 for OS firmware

Downloading macOS OS package info...
.

Creating new stub macOS named LinuxM1
Installing stub macOS into disk0s5 (LinuxM1)
Preparing target volumes...
Checking volumes...
Beginning stub OS install...
++
Setting up System volume...
Setting up Data volume...
Setting up Preboot volume...
+++++++++
Setting up Recovery volume...
++++Error downloading data (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>), retrying... (1/5)
+++++++++++++++++++++++++++++++++++++++++++++++++++++
Wrapping up...

Stub OS installation complete.

Adding partition EFI (500.17 MB)...
  Formatting as FAT...
Adding partition Root (32.00 GB)...
Collecting firmware...
Installing OS...
  Copying from esp into disk0s4 partition...
+
  Copying firmware into disk0s4 partition...
  Extracting root.img into disk0s7 partition...
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++^C
Interrupted

**Comment by maximalisms** [comment]
[](https://github.com/AsahiLinux/asahi-installer/issues/36
)
p.s. a pastebin would have done nicely here

**Comment by maximalisms** [comment]
https://github.com/AsahiLinux/asahi-installer/issues/36#issuecomment-1073341875

**Comment by marcan** [comment]
See [here](https://github.com/AsahiLinux/docs/wiki/Partitioning-cheatsheet) for cleanup instructions. The issue with stuck downloads should also be fixed now, so I think we can close this now.
