### ISSUE TITLE
Blocked in step2: Bputil failed. Did you mistype your password?

### ISSUE THREAD

**Issue by abesombes** [AsahiLinux/asahi-installer#57]
I am trying to install Asahi Linux on my Macbook Air M1. Step1 was OK but I am blocked at step2.sh after the 1TR restart. 
I selected Asahi Linux in the boot menu and my MacOs username, I was prompted for my password, which was ok. Then I arrive in step2.sh terminal window and I am asked again for my password. I put exactly the same as a few seconds before, the system freezes for 5 seconds and then it says: "Local policy update is in progress, please wait... Boot objects update failed for /Volumes/Asahi Linux: Error Domain=BYErrorDomainCode=401 "Failed to create local policy" UserInfo={NSLocalizedDescription=Failed to create local policy, NSUnderlyingError=0x60001c844b0 (Error Domain=com.apple.bootpolicy Code=17 "pairing (17)" UserInfo={NSLocalizeDescription=pairing (17)}}}}
bputil failed. Did you mistype your password?
Please enter to try again.

I tried to use "bless --setBoot --device /dev/disk2ds3 but it replied Bootability failed Error Domain=BYServiceErrorDomain Code=602 "(null)".

I am a bit lost about what to do next. Should I restart the install from scratch?

**Comment by marcan** [comment]
I think you're probably running the wrong `bless` command. Type `diskutil list`, look for the Asahi Linux partition on the list, and use that device name for it.

I don't know why some users are hitting this; it means that the boot volume was somehow either not set or reverted back to macOS between step 1 and step 2. I'm thinking of adding a feature to step2 so it checks for this and runs the bless command for you, and asks you to shut down and try again.

**Comment by abesombes** [comment]
Here is it diskutil list result. I am not sure if all looks good. I tried to use the bless command with disk2s3 and disk0s5 but it does not work
![IMG_20220322_121005](https://user-images.githubusercontent.com/62858013/159469646-58b6170c-4fa8-4fdf-9e98-b6dd36af4acc.jpg)
![IMG20220322120926](https://user-images.githubusercontent.com/62858013/159469654-edc24c38-9c0b-4c4a-9c96-1b88daa77c84.jpg)

.

**Comment by marcan** [comment]
The right option for bless is `disk2s2`, not `disk2s3`. You need the system volume, not the Preboot volume :)

I actually just fixed / worked around this failure case in the installer, so future installs will guide you through resolving this if it happens again!

**Comment by marcan** [comment]
Glad to hear it worked!
