### ISSUE TITLE
[HELP] error I with creating linux on my M1 pro MCBP

### ISSUE THREAD

**Issue by Galorlx** [AsahiLinux/asahi-installer#60]
<img width="563" alt="Screen Shot 2022-03-22 at 2 44 54 PM" src="https://user-images.githubusercontent.com/68242406/159572888-d429e3dd-bd56-4827-a0de-dda8dad0a65c.png">

**Comment by Galorlx** [comment]
> Please attach the log file at `/tmp/asahi-installer/installer.log` so we can take a look.
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/8333635/installer.log)

there's the log

**Comment by WP-LKL** [comment]
> > > I had this error. the problem is that diskutil is a little buggy with this (idk why). you just need to allocate more storage to the Asahi linux storage. I am sure there is a better fix but that is the way I fixed it. I have a 1 TB drive and partitioned 50% to it. Asahi said 38 percent was good for whatever reason, but diskutil clearly wasn't taking it. I didn't want to troubleshoot for hours and I had enough storage to spare so that could be potential solution :)
> > > sorry I couldn't be of much help
> > 
> > Just to add. As described on Twitter some of these installs have been revealing latent corruptions on the disks in some scenarios. I will edit my comment if I find the fix mentioned in the same thread.
> 
> You have anything on that thread?

You can find the discussion here: https://twitter.com/AsahiLinux/status/1505270512213454849?t=d6bh9ybE3qLZQ98CWigtog&s=19

I believe the next step is to improve the easy of debugging and error logs. Hope you get everything working.

**Comment by Galorlx** [comment]
> > > > I had this error. the problem is that diskutil is a little buggy with this (idk why). you just need to allocate more storage to the Asahi linux storage. I am sure there is a better fix but that is the way I fixed it. I have a 1 TB drive and partitioned 50% to it. Asahi said 38 percent was good for whatever reason, but diskutil clearly wasn't taking it. I didn't want to troubleshoot for hours and I had enough storage to spare so that could be potential solution :)
> > > > sorry I couldn't be of much help
> > > 
> > > 
> > > Just to add. As described on Twitter some of these installs have been revealing latent corruptions on the disks in some scenarios. I will edit my comment if I find the fix mentioned in the same thread.
> > 
> > 
> > You have anything on that thread?
> 
> You can find the discussion here: https://twitter.com/AsahiLinux/status/1505270512213454849?t=d6bh9ybE3qLZQ98CWigtog&s=19
> 
> I believe the next step is to improve the easy of debugging and error logs. Hope you get everything working.

Thanks I’ll try this when I get to my computer

**Comment by Galorlx** [comment]
> > > > I had this error. the problem is that diskutil is a little buggy with this (idk why). you just need to allocate more storage to the Asahi linux storage. I am sure there is a better fix but that is the way I fixed it. I have a 1 TB drive and partitioned 50% to it. Asahi said 38 percent was good for whatever reason, but diskutil clearly wasn't taking it. I didn't want to troubleshoot for hours and I had enough storage to spare so that could be potential solution :)
> > > > sorry I couldn't be of much help
> > > 
> > > 
> > > Just to add. As described on Twitter some of these installs have been revealing latent corruptions on the disks in some scenarios. I will edit my comment if I find the fix mentioned in the same thread.
> > 
> > 
> > You have anything on that thread?
> 
> You can find the discussion here: https://twitter.com/AsahiLinux/status/1505270512213454849?t=d6bh9ybE3qLZQ98CWigtog&s=19
> 
> I believe the next step is to improve the easy of debugging and error logs. Hope you get everything working.

Didn’t work :(

**Comment by Galorlx** [comment]
> Please attach the log file at `/tmp/asahi-installer/installer.log` so we can take a look.

I sent the log

**Comment by Galorlx** [comment]
hello?

**Comment by Galorlx** [comment]
@marcan

**Comment by Galorlx** [comment]
@marcan

**Comment by marcan** [comment]
I'm not sure what the problem is; you do have an "Apple_Boot" partition, which is garbage that diskutil creates sometimes, but I don't know why it would've caused this problem. Unfortunately, there was a bug with the installer that caused it not to log enough information to figure out what's wrong. Can you try again, and attach the new log file?

**Comment by Galorlx** [comment]
@marcan 
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/8357664/installer.log)

**Comment by marcan** [comment]
Okay, that still doesn't make any sense. I think this is a diskutil bug.

Please paste the output of the following commands:
```
sudo diskutil list
sudo gpt show /dev/disk0
sudo diskutil addPartition disk0s2 apfs JaxonsLinuxM1 2.5G
```

**Comment by Galorlx** [comment]
sudo diskutil list = "/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         500.3 GB   disk0
   1:             Apple_APFS_ISC ⁨⁩                        524.3 MB   disk0s1
   2:                 Apple_APFS ⁨Container disk3⁩         350.0 GB   disk0s2
                    (free space)                         144.3 GB   -
   3:                 Apple_Boot ⁨Boot OS X⁩               134.2 MB   disk0s3
   4:        Apple_APFS_Recovery ⁨⁩                        5.4 GB     disk0s4

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +350.0 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume ⁨Macintosh HD⁩            15.2 GB    disk3s1
   2:              APFS Snapshot ⁨com.apple.os.update-...⁩ 15.2 GB    disk3s1s1
   3:                APFS Volume ⁨Preboot⁩                 410.9 MB   disk3s2
   4:                APFS Volume ⁨Recovery⁩                799.6 MB   disk3s3
   5:                APFS Volume ⁨Data⁩                    208.3 GB   disk3s5
   6:                APFS Volume ⁨VM⁩                      2.1 GB     disk3s6

/dev/disk4 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +364.2 MB   disk4
   1:                  Apple_HFS ⁨Porting Kit 5.0.8⁩       364.1 MB   disk4s1"

sudo gpt show /dev/disk0 = "start       size  index  contents
          0          1         PMBR
          1          1         Pri GPT header
          2          4         Pri GPT table
          6     128000      1  GPT part - 69646961-6700-11AA-AA11-00306543ECAC
     128006   85449216      2  GPT part - 7C3457EF-0000-11AA-AA11-00306543ECAC
   85577222   35217429         
  120794651      32768      3  GPT part - 426F6F74-0000-11AA-AA11-00306543ECAC
  120827419    1310709      4  GPT part - 52637672-7900-11AA-AA11-00306543ECAC
  122138128          4         Sec GPT table
  122138132          1         Sec GPT header"

sudo diskutil addPartition disk0s2 apfs JaxonsLinuxM1 2.5G = "The new partition to be added will be of a filesystem personality of APFS apfs APFS 7C3457EF-0000-11AA-AA11-00306543ECAC
The new partition will be added following disk0s2
Started partitioning on disk0
Error: -69519: The target disk is too small for this operation, or a gap is required in your partition map which is missing or too small, which is often caused by an attempt to grow a partition beyond the beginning of another partition or beyond the end of partition map usable space" @marcan

**Comment by Galorlx** [comment]
@marcan

**Comment by Galorlx** [comment]
@marcan

**Comment by Galorlx** [comment]
@marcan

**Comment by Galorlx** [comment]
@marcan

**Comment by marcan** [comment]
Repeatedly mentioning me isn't going to make anything go faster. Please don't do that.

This is a diskutil bug. You'll have to file a feedback report with Apple, it's not something we can fix.

On 2022年3月29日 5:30:42 JST, Galorlx ***@***.***> wrote:
***@***.*** 
>

-- 
Hector Martin "marcan" ***@***.***)
Public key: https://mrcn.st/pub

**Comment by Galorlx** [comment]
> Repeatedly mentioning me isn't going to make anything go faster. Please don't do that. This is a diskutil bug. You'll have to file a feedback report with Apple, it's not something we can fix. On 2022年3月29日 5:30:42 JST, Galorlx ***@***.***> wrote: ***@***.***
> […](#)

Apple never helped there diagnosis was “ we need for information with the error your getting when trying to help because the bug makes no sense “ what they mean is they need more information with the asahilinux terminal error and I heard you guys were working on it but it’s been a long time.

**Comment by marcan** [comment]
The bug is that diskutil doesn't work for you where it should. The information in [this comment](https://github.com/AsahiLinux/asahi-installer/issues/60#issuecomment-1079931133) shows that it is a problem with diskutil; it fails to create a partition where it should work. The first command output clearly shows you have free space, yet partition creation fails. This has nothing to do with Asahi Linux; a basic macOS command is failing to do its job for you.

If Apple can't help you diagnose the issue with that information then there's nothing we can do either. These are, unfortunately, the perils of closed-source software. Without being able to reproduce it here, never mind having access to source code, there's no way for us to even begin trying to figure out what's wrong. If it were something hitting a lot of users we'd have to figure something out, but so far it seems you're the only affected user and we just don't have the bandwidth to go on an adventure tracking down a freak Apple bug. This is really something they should fix.
