### ISSUE TITLE
No such file or directory: 'installer_data.json

### ISSUE THREAD

**Issue by kissggj123** [AsahiLinux/asahi-installer#61]
03-23 18:17 root         INFO     Startup
03-23 18:17 root         INFO     Environment:
03-23 18:17 root         INFO       INSTALLER_BASE=None
03-23 18:17 root         INFO       INSTALLER_DATA=None
03-23 18:17 root         INFO       REPO_BASE=None
03-23 18:17 root         INFO       IPSW_BASE=None
03-23 18:17 root         INFO     Version: v0.3.24

03-23 18:17 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/Users/yumikotoys/Downloads/installer-v0.3.24/main.py", line 820, in <module>
    InstallerMain().main()
  File "/Users/yumikotoys/Downloads/installer-v0.3.24/main.py", line 70, in __init__
    self.data = json.load(open("installer_data.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'installer_data.json'
03-23 18:17 root         INFO     MSG: If you need to file a bug report, please attach the log file:
03-23 18:17 root         INFO     MSG:   /Users/yumikotoys/Downloads/installer-v0.3.24/installer.log

**Comment by marcan** [comment]
Sounds like you ran the installer directly, without the bootstrap script. If you do that, you need to set the environment variables correctly to point to the package repositories and installer data file, otherwise it won't know where to find them.
