### ISSUE TITLE
Issue when installing 

### ISSUE THREAD

**Issue by talmax1124** [AsahiLinux/asahi-installer#67]
Failed to run process: diskutil apfs resizeContainer disk0s2 [549999083520](tel:549999083520)
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 820, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 672, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 792, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 612, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '[549999083520](tel:549999083520)']' returned non-zero exit status 1.
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log

Also, I currently have 696.34GB out of 994.66 on my M1 Pro Macbook Pro. I only want to have about 200GB to use for linux. What should I put for size partition in the option?

**Comment by marcan** [comment]
You need to look at the message *before* the "Failed to run process" line to find out what the cause of the issue was. It could be your filesystem is corrupted, or it could be that you have Time Machine snapshots taking up the free space.

**Comment by talmax1124** [comment]
@marcan 

Performing deferred repairs
error: doc-id tree record exists for doc-id 50469, but no inode references this doc-id
Skipped 4/4 repairs of this type in total
Deferred repairs skipped
The container /dev/disk0s2 could not be verified completely
Storage system check exit code is 8
Error: -69716: Storage system verify or repair failed
Failed to run process: diskutil apfs resizeContainer disk0s2 596797030400
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 820, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 672, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 792, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 612, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '596797030400']' returned non-zero exit status 1.
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log

**Comment by talmax1124** [comment]
In the log, it shows:

03-27 02:49 root         INFO       Has OS
03-27 02:49 root         INFO     MSG: We're going to resize this partition:
03-27 02:49 root         INFO     MSG:   APFS [Macintosh HD] (994.66 GB, 6 volumes)
03-27 02:49 root         INFO     MSG:   Total size: [m994.66 GB[m
03-27 02:49 root         INFO     MSG:   Free space: [m701.70 GB[m
03-27 02:49 root         INFO     MSG:   Minimum free space: [m38.00 GB[m
03-27 02:49 root         INFO     MSG:   Minimum total size: [m330.96 GB (33.27%)[m
03-27 02:49 root         INFO     MSG: Enter the new size for your existing partition:
03-27 02:49 root         INFO     MSG:   You can enter a size such as '1GB', a fraction such as '50%',
03-27 02:49 root         INFO     MSG:   or the word 'min' for the smallest allowable size.
03-27 02:49 root         INFO     MSG:   Examples:
03-27 02:49 root         INFO     MSG:   30%  - 30% to macOS, 70% to the new OS
03-27 02:49 root         INFO     MSG:   80GB - 80GB to macOS, the rest to your new OS
03-27 02:49 root         INFO     MSG:   min  - Shrink macOS as much as (safely) possible
03-27 02:49 root         INFO     MSG: [1;37m»[1;36m New size (50%): [m
03-27 02:49 root         INFO     INPUT: '70%'
03-27 02:49 root         INFO     MSG: Resizing will free up 298.40 GB of space.
03-27 02:49 root         INFO     MSG: Note: your system may appear to freeze during the resize.
03-27 02:49 root         INFO     MSG: This is normal, just wait until the process completes.
03-27 02:49 root         INFO     MSG: [1;37m»[1;36m Continue? (y/N): [m
03-27 02:49 root         INFO     INPUT: 'y'
03-27 02:49 root         DEBUG    run: diskutil ('apfs', 'resizeContainer', 'disk0s2', '696262852608')
03-27 02:52 root         INFO     MSG: Failed to run process: diskutil apfs resizeContainer disk0s2 696262852608
03-27 02:52 root         ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 820, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 672, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 792, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 612, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '696262852608']' returned non-zero exit status 1.
03-27 02:52 root         INFO     MSG: If you need to file a bug report, please attach the log file:
03-27 02:52 root         INFO     MSG:   /private/tmp/asahi-install/installer.log

@marcan

**Comment by talmax1124** [comment]
> You need to look at the message _before_ the "Failed to run process" line to find out what the cause of the issue was. It could be your filesystem is corrupted, or it could be that you have Time Machine snapshots taking up the free space.

Any Fixes you know of?

**Comment by marcan** [comment]
That's filesystem corruption. You need to run First Aid from recovery mode. Nothing we can do about it ourselves; it's Apple's buggy APFS code that apparently has been leaving behind silently corrupted filesystems :(
