### ISSUE TITLE
raw.githubusercontent.com blocked in China

### ISSUE THREAD

**Issue by lee5544** [AsahiLinux/asahi-installer#68]
<img width="714" alt="截屏2022-03-27 16 57 21" src="https://user-images.githubusercontent.com/44977031/160274364-bf2b1c78-599e-44aa-b8e8-b2532e2de0ba.png">

**Comment by marcan** [comment]
@zoushibo123 Are you in China by any chance? @lee5544 seems to be and had the same issue, and now I'm wondering if this is some Great Firewall thing. Can you try the command above?

**Comment by zoushibo123** [comment]
Hello，I‘m  in China
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 46 ms: Connection refused

**Comment by zoushibo123** [comment]
> @zoushibo123你在中国吗？@lee5544似乎有同样的问题，现在我想知道这是否是防火墙的问题。你可以试试上面的命令吗？

你好，我在中国
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 46 ms: Connection refused

**Comment by zoushibo123** [comment]
> @zoushibo123你在中国吗？@lee5544似乎有同样的问题，现在我想知道这是否是防火墙的问题。你可以试试上面的命令吗？

当我修改了host文件后，提示下面的错误
![image](https://user-images.githubusercontent.com/102923181/161674807-5d485f6e-187b-4091-aceb-c76489cbce74.png)

**Comment by marcan** [comment]
Looks like a GFW issue then, yeah. Sorry, there's not much we can do about that :(. Maybe try using a VPN?

**Comment by marcan** [comment]
I just pushed a workaround for this, hopefully it works for you. Keep in mind there's only so much we can do against government censorship, though, if they want to block us they will :(
