### ISSUE TITLE
failed to installer，macOS12.3.1,M1,

### ISSUE THREAD

**Issue by zoushibo123** [AsahiLinux/asahi-installer#72]
xiaotaiyang@bogon asahi-installer % curl https://alx.sh | sh                                   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1049  100  1049    0     0    835      0  0:00:01  0:00:01 --:--:--   841

Bootstrapping installer:
  Checking version...
  Version: v0.3.26
  Downloading...
xiaotaiyang@bogon asahi-installer %

**Comment by marcan** [comment]
This is the same as #68, let's move discussion there.
