### ISSUE TITLE
Failed to run bless. Press enter to try again.

### ISSUE THREAD

**Issue by ovalny** [AsahiLinux/asahi-installer#75]
While Asahi was being installed on my Mac, the installer asked for the password from the user a second time and I got this error:
<img width="697" alt="Снимок экрана 2022-04-07 в 20 25 50" src="https://user-images.githubusercontent.com/45847520/162188344-c9be7e9b-0fe1-4052-976a-346e59e827be.png">
I press Enter, but here everything rests

MacBook Air M1

**Comment by utopiatopia** [comment]
What version of MacOS are you running? iirc Marcan said minimum 12.2. Looks like system firmware needs an update.

**Comment by ovalny** [comment]
used 12.2

when i upgraded to 12.4 the problem went away
