### ISSUE TITLE
How should I remove Asahi?

### ISSUE THREAD

**Issue by ovalny** [AsahiLinux/asahi-installer#76]
The Asahi website says that it is enough to delete disk partitions using diskutil. If I delete the Asahi disk partitions, will the Mac boot my macOS and won't bricking? Or do I need to take some other steps?

**Comment by marcan** [comment]
It is recommended that you set the default boot OS to macOS first. You can do that from the macOS system settings, under Startup Disk.

**Comment by ovalny** [comment]
and then just delete the partitions?

**Comment by leifliddy** [comment]
Yes. The easiest way to remove the Linux partitions is to boot to macOS and run this script. 
```curl -L https://alx.sh/wipe-linux | sh```
You should understand what the script does before running it at it will indiscriminately wipe anything with "Linux", "EFI" or "Asahi" in its name, as well as all 2.5GB APFS containers. 

Or....you could just modify that script with echo statements ie 
```
diskutil list | grep Apple_APFS | grep '\b2\.5 GB' | sed 's/.* //g' | while read i; do
    echo "diskutil apfs deleteContainer $i"
done
diskutil list /dev/disk0 | grep -Ei 'asahi|linux|EFI' | sed 's/.* //g' | while read i; do
    echo "diskutil eraseVolume free free $i"
done
```
...and then verify those commands are correct and run them manually. However you want to do it.

You can read more about disk partitioning here.
https://github.com/AsahiLinux/docs/wiki/Partitioning-cheatsheet

**Comment by ovalny** [comment]
thank you!

**Comment by Jeremy-JYL** [comment]
And it echo a "This script is dangerous and you shouldn't be using it."

#!/bin/sh

echo "This script is dangerous and you shouldn't be using it." 1>&2
exit 1

**Comment by SudoTheHacker** [comment]
@codenyte @abc-JYL 
https://raw.githubusercontent.com/AsahiLinux/asahi-installer/main/tools/wipe-linux.sh
I think it's pretty clear, but it's dangerous, read it first and then run if you understood every single line. Personally, I would read the script and manually do what the script does (just to be safe).
