### ISSUE TITLE
A problem occurred while resizing APFS Container structures

### ISSUE THREAD

**Issue by mlacks** [AsahiLinux/asahi-installer#85]
Error: -69606: A problem occurred while resizing APFS Container structures
Failed to run process: diskutil apfs resizeContainer disk0s2 171574296576

[installer.log](https://github.com/AsahiLinux/docs/files/8403239/installer.log)

**Comment by marcan** [comment]
This is a duplicate of either #81 or #86, depending on whether the message above that error mentioned Time Machine or not.
