### ISSUE TITLE
Can't use precreated partition

### ISSUE THREAD

**Issue by yoe** [AsahiLinux/asahi-installer#90]
I had planned to install Linux on my M1 mac a while ago, but didn't get around to it, mostly because of the high amount of manual work that was required. I had gotten the first step done -- create a partition -- but that was it.

I saw the announcement for the installer the other day, so thought I'd have a look. So I start the installer, and I'm given this screen:

```
Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (225.11 GB, 6 volumes)
    OS: [B*] [Macintosh HD ] macOS v12.3.1 [disk4s1, 355AE13A-D811-48B5-9096-1B230A4A49E0]
  2: APFS [Linux] (20.00 GB, 1 volujme)
  3: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v12.3.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk4s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
```

The option I would need, "wipe an existing partition and use its space" does not exist.

Looking in the python code of the installer, I see there's an option to use "free space" on the disk; however, the Apple partitioner in `Disk Utility.app` does not allow one to create empty space; reducing the size of an existing APFS partition will immediately create a new partition (APFS by default); it's not possible to tell the partitioner to not do that, AFAICS.

It would be preferable if I could tell the installer to repurpose an existing partition, if one exists that is not the system disk nor the recovery partition.

**Comment by leifliddy** [comment]
You can wipe the existing EFI + Linux partition with this method.
https://github.com/AsahiLinux/asahi-installer/issues/76#issuecomment-1094359888
