### ISSUE TITLE
`curl https://alx.sh | bash` does not do the installation

### ISSUE THREAD

**Issue by chenrui333** [AsahiLinux/asahi-installer#98]
Not sure if this is just my issue, but I could not do `curl https://alx.sh | bash` to install the page.

The `https://alx.sh` got redirected to `https://asahilinux.org`

```bash
$ curl -I https://alx.sh
HTTP/2 302
server: nginx/1.21.1
date: Fri, 03 Jun 2022 22:29:58 GMT
content-type: text/html
content-length: 145
location: https://asahilinux.org
strict-transport-security: max-age=31536000;
```

Thanks!

**Comment by marcan** [comment]
```<snip> - - [03/Jun/2022:22:29:58 +0000] "HEAD / HTTP/2.0" 302 114 "-" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)" "-"```

That's a mighty strange version of curl you have there, it thinks it's Internet Explorer!

**Comment by marcan** [comment]
FYI, you can use `curl -L https://alx.sh/prod | sh` if the user agent check is an issue for you. We do that so that people who mistakenly open it up in a browser get a useful info page instead of a .sh dumped at them.

**Comment by chenrui333** [comment]
> FYI, you can use `curl -L https://alx.sh/prod | sh` if the user agent check is an issue for you. 

This works for me well.

**Comment by chenrui333** [comment]
I think I am all set, thanks @marcan!

**Comment by chenrui333** [comment]
actually I cannot finish the last step (after the machine restart):

```
Can't load ../apfs.efi
Could not load apfs.efi data from xxx
```

**Comment by marcan** [comment]
What version of macOS are you running?
